# Generated by Django 3.2.4 on 2022-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='店铺名称', max_length=80, verbose_name='店铺名称')),
                ('type', models.CharField(choices=[('WAREHOUSE', '仓库'), ('STORE', '门店')], default='STORE', help_text='店铺类型', max_length=10, verbose_name='店铺类型')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=200, null=True, verbose_name='地址')),
                ('contact_name', models.CharField(blank=True, help_text='联系人', max_length=20, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=15, null=True, verbose_name='电话')),
                ('qq', models.CharField(blank=True, help_text='QQ', max_length=15, null=True, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, help_text='微信', max_length=15, null=True, verbose_name='微信')),
                ('website', models.CharField(blank=True, help_text='网址', max_length=200, null=True, verbose_name='网址')),
                ('is_active', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '销售门店',
                'verbose_name_plural': '销售门店',
                'ordering': ['-create_time'],
            },
        ),
    ]
