# Generated by Django 3.2.4 on 2022-03-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_supplier_email'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='库存数量', verbose_name='库存数量')),
                ('lock_qty', models.IntegerField(default=0, help_text='锁定库存量', verbose_name='锁定库存量')),
                ('avg_sales', models.FloatField(default=0.0, help_text='日均销量', verbose_name='日均销量')),
                ('recent_7d_sales', models.IntegerField(default=0, help_text='最近7天销量', verbose_name='最近7天销量')),
                ('recent_30d_sales', models.IntegerField(default=0, help_text='最近30天销量', verbose_name='最近30天销量')),
                ('last_sale_time', models.DateTimeField(help_text='最后一次销售时间', null=True, verbose_name='最后一次销售时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='product.product', verbose_name='产品')),
                ('store', models.ForeignKey(help_text='门店', on_delete=django.db.models.deletion.CASCADE, related_name='store_stock', to='store.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '产品库存',
                'verbose_name_plural': '产品库存',
                'ordering': ['-create_time'],
            },
        ),
    ]
