# Generated by Django 3.2.4 on 2022-03-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_alter_stock_last_sale_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='批次号', max_length=15, verbose_name='批次号')),
                ('type', models.CharField(choices=[('IN', '入库'), ('OUT', '出库'), ('MOVE', '调拨')], default='IN', help_text='类型', max_length=10, verbose_name='类型')),
                ('reason_in', models.CharField(choices=[('RETURN', '客户退货'), ('OTHERS', '其它原因')], default='RETURN', help_text='入库原因', max_length=10, verbose_name='入库原因')),
                ('reason_out', models.CharField(choices=[('GIFT', '非销售出库'), ('LOST', '丢失'), ('OTHERS', '其它原因')], default='LOST', help_text='出库原因', max_length=10, verbose_name='出库原因')),
                ('reason_move', models.CharField(choices=[('SUPPORT', '库存支援'), ('OTHERS', '其它原因')], default='SUPPORT ', help_text='调拨原因', max_length=10, verbose_name='调拨原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('origin_store', models.ForeignKey(help_text='源仓库/店铺', on_delete=django.db.models.deletion.CASCADE, related_name='store_inout_or', to='store.store', verbose_name='源仓库/店铺')),
                ('target_store', models.ForeignKey(help_text='目标仓库/店铺', on_delete=django.db.models.deletion.CASCADE, related_name='store_inout_ta', to='store.store', verbose_name='目标仓库/店铺')),
                ('user', models.ForeignKey(help_text='操作人', on_delete=django.db.models.deletion.CASCADE, related_name='user_store_inout', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '手工出入库/调拨',
                'verbose_name_plural': '手工出入库/调拨',
                'ordering': ['-create_time'],
            },
        ),
    ]
