# Generated by Django 3.2.4 on 2022-03-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_supplier_email'),
        ('store', '0005_stockinout'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInOutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='出入数量', verbose_name='出入数量')),
                ('stock_before', models.IntegerField(default=0, help_text='变动前库存', verbose_name='变动前库存')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_inout_detail', to='product.product', verbose_name='产品')),
                ('stock_in_out', models.ForeignKey(help_text='所属出入库单', on_delete=django.db.models.deletion.CASCADE, related_name='inout_detail', to='store.stockinout', verbose_name='所属出入库单')),
            ],
            options={
                'verbose_name': '出入库产品明细',
                'verbose_name_plural': '出入库产品明细',
                'ordering': ['id'],
            },
        ),
    ]
