# Generated by Django 3.2.4 on 2022-03-29 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_stockinoutdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinout',
            name='user',
            field=models.ForeignKey(help_text='操作人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_store_inout', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
