# Generated by Django 3.2.4 on 2022-03-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_stockinout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinout',
            name='batch_number',
            field=models.CharField(help_text='批次号', max_length=20, verbose_name='批次号'),
        ),
    ]
