# Generated by Django 3.2.4 on 2022-03-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_stockinout_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinout',
            name='origin_store',
            field=models.ForeignKey(help_text='源仓库/店铺', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_inout_or', to='store.store', verbose_name='源仓库/店铺'),
        ),
        migrations.AlterField(
            model_name='stockinout',
            name='target_store',
            field=models.ForeignKey(help_text='目标仓库/店铺', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_inout_ta', to='store.store', verbose_name='目标仓库/店铺'),
        ),
    ]
