# Generated by Django 3.2.4 on 2022-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220329_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinout',
            name='batch_number',
            field=models.CharField(help_text='批次号', max_length=30, verbose_name='批次号'),
        ),
    ]
