# Generated by Django 3.2.4 on 2022-04-03 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_label_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_alter_stockinout_batch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(choices=[('M_IN', '手工入库'), ('M_OUT', '手工出库'), ('S_OUT', '销售出库'), ('LOCK', '锁仓'), ('UNLOCK', '解锁')], default='S_OUT', help_text='日志类型', max_length=10, verbose_name='日志类型')),
                ('op_log', models.TextField(blank=True, default='', help_text='操作描述', null=True, verbose_name='操作描述')),
                ('qty', models.IntegerField(blank=True, default=0, help_text='数量', null=True, verbose_name='数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='操作时间', verbose_name='操作时间')),
                ('product', models.ForeignKey(help_text='产品', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_stock_log', to='product.product', verbose_name='产品')),
                ('store', models.ForeignKey(help_text='店铺', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_stock_log', to='store.store', verbose_name='店铺')),
                ('user', models.ForeignKey(help_text='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_stock_log', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '库存出入日志',
                'verbose_name_plural': '库存出入日志',
                'ordering': ['-create_time'],
            },
        ),
    ]
