# Generated by Django 3.2.4 on 2022-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_stocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='op_log',
            field=models.CharField(blank=True, help_text='操作描述', max_length=200, null=True, verbose_name='操作描述'),
        ),
    ]
