# Generated by Django 3.2.4 on 2022-04-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220403_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinout',
            name='note',
            field=models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注'),
        ),
    ]
