# Generated by Django 3.2.4 on 2022-04-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_stockinout_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinout',
            name='reason_move',
            field=models.CharField(choices=[('SUPPORT', '库存支援'), ('OTHERS', '其它原因')], default='SUPPORT', help_text='调拨原因', max_length=10, verbose_name='调拨原因'),
        ),
    ]
