# Generated by Django 3.2.4 on 2022-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_stocklog_op_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinout',
            name='type',
            field=models.CharField(choices=[('IN', '入库'), ('OUT', '出库'), ('MOVE', '调拨'), ('TAKING', '盘点')], default='IN', help_text='类型', max_length=10, verbose_name='类型'),
        ),
    ]
