# Generated by Django 3.2.4 on 2022-05-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_stockinout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='op_type',
            field=models.CharField(choices=[('M_IN', '手工入库'), ('M_OUT', '手工出库'), ('B_IN', '采购入库'), ('S_OUT', '销售出库'), ('LOCK', '锁仓'), ('UNLOCK', '解锁'), ('TAKING', '库存盘点')], default='S_OUT', help_text='日志类型', max_length=10, verbose_name='日志类型'),
        ),
    ]
