[uwsgi]
chdir = /app
module = casedance.wsgi:application
master = true
processes = 1
threads = 2
http = 0.0.0.0:8000
vacuum = true
max-requests = 2000
max-worker-lifetime = 1800
reload-on-rss = 200
buffer-size = 32768
