# Generated by Django 3.2.4 on 2022-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BRAND', '品牌'), ('SERIES', '系列'), ('P_TYPE', '产品类型')], default='SERIES', help_text='信息类型', max_length=10, verbose_name='信息类型')),
                ('name', models.CharField(help_text='信息名称', max_length=30, verbose_name='信息名称')),
            ],
            options={
                'verbose_name': '产品附属信息',
                'verbose_name_plural': '产品附属信息',
            },
        ),
    ]
