# Generated by Django 3.2.4 on 2022-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productextrainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.CharField(blank=True, help_text='产品类型', max_length=30, null=True, verbose_name='产品类型'),
        ),
    ]
