# Generated by Django 3.2.4 on 2022-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_p_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='品牌', max_length=20, null=True, verbose_name='品牌')),
                ('type', models.CharField(blank=True, help_text='类型', max_length=20, null=True, verbose_name='类型')),
                ('model', models.CharField(help_text='型号', max_length=40, verbose_name='型号')),
            ],
            options={
                'verbose_name': '市面手机型号表',
                'verbose_name_plural': '市面手机型号表',
            },
        ),
    ]
