# Generated by Django 3.2.4 on 2022-03-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_devicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model', models.ForeignKey(help_text='市面手机型号', on_delete=django.db.models.deletion.DO_NOTHING, to='product.devicemodel', verbose_name='市面手机型号')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品兼容手机型号',
                'verbose_name_plural': '产品兼容手机型号',
            },
        ),
    ]
