# Generated by Django 3.2.4 on 2022-03-27 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_tag_options'),
        ('product', '0006_auto_20220327_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productextrainfo',
            options={'ordering': ['id'], 'verbose_name': '产品附属信息', 'verbose_name_plural': '产品附属信息'},
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, related_name='product_p_tag', to='product.product', verbose_name='产品')),
                ('tag', models.ForeignKey(help_text='标签', on_delete=django.db.models.deletion.CASCADE, related_name='tag_p_tag', to='setting.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '产品标签表',
                'verbose_name_plural': '产品标签表',
                'ordering': ['id'],
            },
        ),
    ]
