# Generated by Django 3.2.4 on 2022-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220327_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='供应商名称', max_length=80, verbose_name='供应商名称')),
                ('buy_way', models.CharField(choices=[('FACTORY', '工厂'), ('1688', '1688'), ('OTHERS', '其它')], default='FACTORY', help_text='采购渠道', max_length=10, verbose_name='采购渠道')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=200, null=True, verbose_name='地址')),
                ('contact_name', models.CharField(blank=True, help_text='联系人', max_length=20, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=15, null=True, verbose_name='电话')),
                ('qq', models.CharField(blank=True, help_text='QQ', max_length=15, null=True, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, help_text='微信', max_length=15, null=True, verbose_name='微信')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=15, null=True, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注'),
        ),
    ]
