# Generated by Django 3.2.4 on 2022-03-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220328_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, help_text='邮箱', max_length=50, null=True, verbose_name='邮箱'),
        ),
    ]
