# Generated by Django 3.2.4 on 2022-05-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20220413_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='cp_id',
            field=models.IntegerField(blank=True, help_text='兼容识别码', null=True, verbose_name='兼容识别码'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='note',
            field=models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注'),
        ),
    ]
