# Generated by Django 3.2.4 on 2022-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220503_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='品牌名称', max_length=30, verbose_name='品牌名称')),
                ('link', models.CharField(help_text='链接', max_length=150, verbose_name='链接')),
            ],
            options={
                'verbose_name': '市面手机品牌',
                'verbose_name_plural': '市面手机品牌',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='announced',
            field=models.CharField(blank=True, help_text='发布时间', max_length=50, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='dimensions',
            field=models.CharField(blank=True, help_text='尺寸', max_length=50, null=True, verbose_name='尺寸'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='image',
            field=models.CharField(blank=True, help_text='型号图片', max_length=300, null=True, verbose_name='型号图片'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='link',
            field=models.CharField(blank=True, help_text='链接', max_length=150, null=True, verbose_name='链接'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(blank=True, help_text='状态', max_length=50, null=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='weight',
            field=models.CharField(blank=True, help_text='重量', max_length=50, null=True, verbose_name='重量'),
        ),
    ]
