# Generated by Django 3.2.4 on 2022-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220519_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='image',
            field=models.ImageField(blank=True, help_text='型号图片', max_length=200, null=True, upload_to='', verbose_name='型号图片'),
        ),
    ]
