# Generated by Django 3.2.4 on 2022-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_devicemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='image',
            field=models.CharField(blank=True, help_text='型号图片', max_length=250, null=True, verbose_name='型号图片'),
        ),
    ]
