# Generated by Django 3.2.4 on 2022-05-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_devicemodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'ordering': ['-create_time'], 'verbose_name': '市面手机型号表', 'verbose_name_plural': '市面手机型号表'},
        ),
    ]
