# Generated by Django 3.2.4 on 2022-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_devicemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='detail_model',
            field=models.CharField(blank=True, default='', help_text='详细型号', max_length=100, null=True, verbose_name='详细型号'),
        ),
    ]
