# Generated by Django 3.2.4 on 2022-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_devicemodel_detail_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='dimensions',
            field=models.CharField(blank=True, help_text='尺寸', max_length=100, null=True, verbose_name='尺寸'),
        ),
    ]
