# Generated by Django 3.2.4 on 2022-05-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='总销量', verbose_name='总销量')),
                ('amount', models.FloatField(default=0.0, help_text='销售金额', verbose_name='销售金额')),
                ('series', models.FloatField(default=0.0, help_text='产品系列', verbose_name='产品系列')),
                ('sale_date', models.DateTimeField(blank=True, help_text='销售日期', null=True, verbose_name='销售日期')),
            ],
            options={
                'verbose_name': '销量统计',
                'verbose_name_plural': '销量统计',
                'ordering': ['sale_date'],
            },
        ),
    ]
