# Generated by Django 3.2.4 on 2022-05-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='sale_date',
            field=models.DateField(blank=True, help_text='销售日期', null=True, verbose_name='销售日期'),
        ),
    ]
