# Generated by Django 3.2.4 on 2022-05-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_salesreport_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='series',
            field=models.CharField(blank=True, help_text='产品系列', max_length=30, null=True, verbose_name='产品系列'),
        ),
    ]
