# Generated by Django 3.2.4 on 2022-06-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_salesreport_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='库存量', verbose_name='库存量')),
                ('amount', models.FloatField(default=0.0, help_text='库存金额', verbose_name='库存金额')),
                ('series', models.CharField(blank=True, help_text='产品系列', max_length=30, null=True, verbose_name='产品系列')),
                ('stock_date', models.DateField(blank=True, help_text='库存日期', null=True, verbose_name='库存日期')),
            ],
            options={
                'verbose_name': '库存统计',
                'verbose_name_plural': '库存统计',
                'ordering': ['stock_date'],
            },
        ),
    ]
