# Generated by Django 3.2.4 on 2022-06-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_alter_order_order_status'),
        ('report', '0004_stockreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='购买量', verbose_name='购买量')),
                ('amount', models.FloatField(default=0.0, help_text='购买金额', verbose_name='购买金额')),
                ('series', models.CharField(blank=True, help_text='产品系列', max_length=30, null=True, verbose_name='产品系列')),
                ('calc_date', models.DateField(blank=True, help_text='统计日期', null=True, verbose_name='统计日期')),
                ('customer', models.ForeignKey(help_text='客户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_report', to='sale.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户销量统计报告',
                'verbose_name_plural': '客户销量统计报告',
                'ordering': ['-qty'],
            },
        ),
    ]
