# Generated by Django 3.2.4 on 2022-06-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_customerreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreport',
            options={'ordering': ['-calc_date'], 'verbose_name': '客户销量统计报告', 'verbose_name_plural': '客户销量统计报告'},
        ),
    ]
