# Generated by Django 3.2.4 on 2022-06-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_customerreport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreport',
            name='amount',
            field=models.FloatField(default=0.0, help_text='累积购买金额', verbose_name='累积购买金额'),
        ),
        migrations.AlterField(
            model_name='customerreport',
            name='qty',
            field=models.IntegerField(default=0, help_text='累积购买量', verbose_name='累积购买量'),
        ),
    ]
