# Generated by Django 3.2.4 on 2022-06-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_devicemodel_options'),
        ('report', '0007_auto_20220603_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='产品销量', verbose_name='产品销量')),
                ('amount', models.FloatField(default=0.0, help_text='产品销售额', verbose_name='产品销售额')),
                ('calc_date', models.DateField(blank=True, help_text='统计日期', null=True, verbose_name='统计日期')),
                ('product', models.ForeignKey(help_text='产品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_report', to='product.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '统计产品每天销量',
                'verbose_name_plural': '统计产品每天销量',
                'ordering': ['-calc_date'],
            },
        ),
    ]
