# Generated by Django 3.2.4 on 2022-03-30 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_auto_20220329_2246'),
        ('product', '0009_alter_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_number', models.CharField(help_text='采购单号', max_length=20, verbose_name='采购单号')),
                ('logistic', models.CharField(blank=True, help_text='发货物流公司', max_length=20, null=True, verbose_name='发货物流公司')),
                ('tracking_number', models.CharField(blank=True, help_text='快递单号', max_length=30, null=True, verbose_name='快递单号')),
                ('postage', models.FloatField(default=0.0, help_text='采购运费', verbose_name='采购运费')),
                ('total_cost', models.FloatField(default=0.0, help_text='采购单总金额', verbose_name='采购单总金额')),
                ('total_paid', models.FloatField(default=0.0, help_text='已结算总金额', verbose_name='已结算总金额')),
                ('paid_status', models.CharField(choices=[('UNPAID', '未结算'), ('PART_PAID', '部分结算'), ('FULL_PAID', '全部结算')], default='UNPAID', help_text='结算状态', max_length=20, verbose_name='结算状态')),
                ('order_status', models.CharField(choices=[('PRE_SUMMIT', '未提交'), ('WAIT_CONFIRM', '待确认'), ('IN_PRODUCTION', '生产中'), ('SENT', '已发货'), ('FINISHED', '已完成'), ('EXCEPTION', '异常')], default='PRE_SUMMIT', help_text='采购单状态', max_length=20, verbose_name='采购单状态')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('store', models.ForeignKey(help_text='收货仓库/店铺', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_purchase_order', to='store.store', verbose_name='收货仓库/店铺')),
                ('supplier', models.ForeignKey(help_text='供应商', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_purchase_order', to='product.supplier', verbose_name='供应商')),
                ('user', models.ForeignKey(help_text='操作人', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_purchase_order', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='采购数量', verbose_name='采购数量')),
                ('unit_cost', models.FloatField(default=0.0, help_text='采购单价', verbose_name='采购单价')),
                ('received_qty', models.IntegerField(default=0, help_text='收货入库数量', verbose_name='收货入库数量')),
                ('is_paid', models.BooleanField(default=False, help_text='是否已结算', verbose_name='是否已结算')),
                ('short_note', models.CharField(blank=True, default='', help_text='简短备注', max_length=100, null=True, verbose_name='简短备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('stock_before', models.IntegerField(default=0, help_text='采购前库存', verbose_name='采购前库存')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_purchase_detail', to='product.product', verbose_name='产品')),
                ('purchase_order', models.ForeignKey(help_text='所属采购单', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_detail', to='purchase.purchaseorder', verbose_name='所属采购单')),
            ],
            options={
                'verbose_name': '采购商品明细',
                'verbose_name_plural': '采购商品明细',
                'ordering': ['create_time'],
            },
        ),
    ]
