# Generated by Django 3.2.4 on 2022-03-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_status',
            field=models.CharField(choices=[('CANCEL', '作废'), ('WAIT_CONFIRM', '待确认'), ('IN_PRODUCTION', '生产中'), ('SENT', '已发货'), ('FINISHED', '已完成'), ('EXCEPTION', '异常')], default='WAIT_CONFIRM', help_text='采购单状态', max_length=20, verbose_name='采购单状态'),
        ),
    ]
