# Generated by Django 3.2.4 on 2022-03-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchaseorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='paid_qty',
            field=models.IntegerField(default=0, help_text='已结算数量', verbose_name='已结算数量'),
        ),
    ]
