# Generated by Django 3.2.4 on 2022-03-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_alter_operatelog_op_log'),
        ('purchase', '0006_auto_20220331_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.ForeignKey(help_text='采购单', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_p_tag', to='purchase.purchaseorder', verbose_name='采购单')),
                ('tag', models.ForeignKey(help_text='标签', on_delete=django.db.models.deletion.CASCADE, related_name='tag_purchase_tag', to='setting.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '采购单标签表',
                'verbose_name_plural': '采购单标签表',
                'ordering': ['id'],
            },
        ),
    ]
