# Generated by Django 3.2.4 on 2022-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_purchaseordertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='p_number',
            field=models.CharField(help_text='采购单号', max_length=30, verbose_name='采购单号'),
        ),
    ]
