# Generated by Django 3.2.4 on 2022-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_purchaseorder_p_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='inner_case_price',
            field=models.FloatField(default=0.0, help_text='素材壳价格', null=True, verbose_name='素材壳价格'),
        ),
    ]
