# Generated by Django 3.2.4 on 2022-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_purchaseorder_inner_case_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='urgent',
            field=models.BooleanField(default=False, help_text='是否加急', verbose_name='是否加急'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rec_address',
            field=models.CharField(blank=True, help_text='收件地址', max_length=200, null=True, verbose_name='收件地址'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rec_name',
            field=models.CharField(blank=True, help_text='收件人', max_length=30, null=True, verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rec_phone',
            field=models.CharField(blank=True, help_text='收件人', max_length=30, null=True, verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sup_tips',
            field=models.TextField(blank=True, default='', help_text='公告提示', null=True, verbose_name='公告提示'),
        ),
    ]
