# Generated by Django 3.2.4 on 2022-04-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_purchaseorder_package_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='logistic',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='package_count',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tracking_number',
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistic', models.CharField(blank=True, help_text='发货物流公司', max_length=20, null=True, verbose_name='发货物流公司')),
                ('tracking_number', models.CharField(blank=True, help_text='快递单号', max_length=30, null=True, verbose_name='快递单号')),
                ('package_count', models.IntegerField(default=0, help_text='发货箱数', verbose_name='发货箱数')),
                ('post_time', models.DateTimeField(auto_now_add=True, help_text='发货时间', verbose_name='发货时间')),
                ('purchase_order', models.ForeignKey(help_text='采购单', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_post_info', to='purchase.purchaseorder', verbose_name='采购单')),
            ],
            options={
                'verbose_name': '采购发货物流信息',
                'verbose_name_plural': '采购发货物流信息',
                'ordering': ['post_time'],
            },
        ),
    ]
