# Generated by Django 3.2.4 on 2022-06-11 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLATFORM', '平台'), ('BASE', '平台站点')], default='PLATFORM', help_text='信息类型', max_length=10, verbose_name='信息类型')),
                ('name', models.CharField(blank=True, help_text='信息名称', max_length=30, null=True, verbose_name='信息名称')),
            ],
            options={
                'verbose_name': '基础信息设置',
                'verbose_name_plural': '基础信息设置',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, help_text='币种', max_length=10, null=True, verbose_name='币种')),
                ('rate', models.FloatField(blank=True, help_text='汇率值', null=True, verbose_name='汇率值')),
                ('month', models.CharField(blank=True, help_text='月份', max_length=10, null=True, verbose_name='月份')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='负责人名称', max_length=30, null=True, verbose_name='负责人名称')),
                ('is_leader', models.BooleanField(default=False, help_text='是否组长', verbose_name='是否组长')),
                ('bonus_rate', models.FloatField(blank=True, help_text='提成点数', null=True, verbose_name='提成点数')),
                ('team', models.IntegerField(blank=True, default=1, help_text='所属小组', null=True, verbose_name='所属小组')),
            ],
            options={
                'verbose_name': '运营负责人',
                'verbose_name_plural': '运营负责人',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='AccountSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, help_text='平台', max_length=30, null=True, verbose_name='平台')),
                ('platform_base', models.CharField(blank=True, help_text='平台站点', max_length=30, null=True, verbose_name='平台站点')),
                ('account_name', models.CharField(blank=True, help_text='账号名称', max_length=30, null=True, verbose_name='账号名称')),
                ('month', models.CharField(blank=True, help_text='月份', max_length=10, null=True, verbose_name='月份')),
                ('sale_amount', models.FloatField(blank=True, help_text='销售额 (原始货币)', null=True, verbose_name='销售额 (原始货币)')),
                ('sale_currency', models.CharField(blank=True, help_text='销售额币种', max_length=10, null=True, verbose_name='销售额币种')),
                ('receipts', models.FloatField(blank=True, help_text='净收款 (原始货币)', null=True, verbose_name='净收款 (原始货币)')),
                ('receipts_currency', models.CharField(blank=True, help_text='净收款币种', max_length=10, null=True, verbose_name='净收款币种')),
                ('refund', models.FloatField(blank=True, help_text='退款(原始货币)', null=True, verbose_name='退款(原始货币)')),
                ('refund_currency', models.CharField(blank=True, help_text='退款币种', max_length=10, null=True, verbose_name='退款币种')),
                ('FES', models.FloatField(blank=True, help_text='结汇收入(人民币)', null=True, verbose_name='结汇收入(人民币)')),
                ('platform_fees', models.FloatField(blank=True, help_text='平台费用 (原始货币)', null=True, verbose_name='平台费用 (原始货币)')),
                ('platform_fees_currency', models.CharField(blank=True, help_text='平台费用币种', max_length=10, null=True, verbose_name='平台费用币种')),
                ('product_cost', models.FloatField(blank=True, help_text='产品成本 (人民币)', null=True, verbose_name='产品成本 (人民币)')),
                ('shipping_cost', models.FloatField(blank=True, help_text='物流成本(人民币)', null=True, verbose_name='物流成本(人民币)')),
                ('profit', models.FloatField(blank=True, help_text='毛利润(人民币)', null=True, verbose_name='毛利润(人民币)')),
                ('profit_margin', models.FloatField(blank=True, help_text='毛利率', null=True, verbose_name='毛利率')),
                ('month_profit', models.FloatField(blank=True, help_text='当月毛利润(人民币)', null=True, verbose_name='当月毛利润(人民币)')),
                ('orders', models.IntegerField(blank=True, default=0, help_text='订单数', null=True, verbose_name='订单数')),
                ('CUP', models.FloatField(blank=True, help_text='平均客单价', null=True, verbose_name='平均客单价')),
                ('ad_fees', models.FloatField(blank=True, help_text='广告费(原始货币)', null=True, verbose_name='广告费(原始货币)')),
                ('ad_fees_currency', models.CharField(blank=True, help_text='平台费用币种', max_length=10, null=True, verbose_name='平台费用币种')),
                ('cp_cgf_fees', models.FloatField(blank=True, help_text='CGFE费用', null=True, verbose_name='CGFE费用')),
                ('cp_first_ship', models.FloatField(blank=True, help_text='CGF发仓运费', null=True, verbose_name='CGF发仓运费')),
                ('manager', models.ForeignKey(help_text='账号负责人', on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_sales', to='bonus.manager', verbose_name='账号负责人')),
            ],
            options={
                'verbose_name': '账号销售报表',
                'verbose_name_plural': '账号销售报表',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='AccountBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, help_text='平台', max_length=30, null=True, verbose_name='平台')),
                ('platform_base', models.CharField(blank=True, help_text='平台站点', max_length=30, null=True, verbose_name='平台站点')),
                ('account_name', models.CharField(blank=True, help_text='账号名称', max_length=30, null=True, verbose_name='账号名称')),
                ('month', models.CharField(blank=True, help_text='月份', max_length=10, null=True, verbose_name='月份')),
                ('sale_amount', models.FloatField(blank=True, help_text='销售额 (原始货币)', null=True, verbose_name='销售额 (原始货币)')),
                ('sale_currency', models.CharField(blank=True, help_text='销售额币种', max_length=10, null=True, verbose_name='销售额币种')),
                ('receipts', models.FloatField(blank=True, help_text='净收款 (原始货币)', null=True, verbose_name='净收款 (原始货币)')),
                ('receipts_currency', models.CharField(blank=True, help_text='净收款币种', max_length=10, null=True, verbose_name='净收款币种')),
                ('refund', models.FloatField(blank=True, help_text='退款(原始货币)', null=True, verbose_name='退款(原始货币)')),
                ('refund_currency', models.CharField(blank=True, help_text='退款币种', max_length=10, null=True, verbose_name='退款币种')),
                ('FES', models.FloatField(blank=True, help_text='结汇收入(人民币)', null=True, verbose_name='结汇收入(人民币)')),
                ('platform_fees', models.FloatField(blank=True, help_text='平台费用 (原始货币)', null=True, verbose_name='平台费用 (原始货币)')),
                ('platform_fees_currency', models.CharField(blank=True, help_text='平台费用币种', max_length=10, null=True, verbose_name='平台费用币种')),
                ('product_cost', models.FloatField(blank=True, help_text='产品成本 (人民币)', null=True, verbose_name='产品成本 (人民币)')),
                ('shipping_cost', models.FloatField(blank=True, help_text='物流成本(人民币)', null=True, verbose_name='物流成本(人民币)')),
                ('profit', models.FloatField(blank=True, help_text='毛利润(人民币)', null=True, verbose_name='毛利润(人民币)')),
                ('profit_margin', models.FloatField(blank=True, help_text='毛利率', null=True, verbose_name='毛利率')),
                ('month_profit', models.FloatField(blank=True, help_text='当月毛利润(人民币)', null=True, verbose_name='当月毛利润(人民币)')),
                ('orders', models.IntegerField(blank=True, default=0, help_text='订单数', null=True, verbose_name='订单数')),
                ('CUP', models.FloatField(blank=True, help_text='平均客单价', null=True, verbose_name='平均客单价')),
                ('ad_fees', models.FloatField(blank=True, help_text='广告费(原始货币)', null=True, verbose_name='广告费(原始货币)')),
                ('ad_fees_currency', models.CharField(blank=True, help_text='平台费用币种', max_length=10, null=True, verbose_name='平台费用币种')),
                ('cp_cgf_fees', models.FloatField(blank=True, help_text='CGFE费用', null=True, verbose_name='CGFE费用')),
                ('cp_first_ship', models.FloatField(blank=True, help_text='CGF发仓运费', null=True, verbose_name='CGF发仓运费')),
                ('bonus_rate', models.FloatField(blank=True, help_text='提成点数', null=True, verbose_name='提成点数')),
                ('is_calc', models.BooleanField(default=False, help_text='是否记入提成', verbose_name='是否记入提成')),
                ('manager', models.ForeignKey(help_text='账号负责人', on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_bonus', to='bonus.manager', verbose_name='账号负责人')),
            ],
            options={
                'verbose_name': '提成表',
                'verbose_name_plural': '提成表',
                'ordering': ['-month'],
            },
        ),
    ]
