# Generated by Django 3.2.4 on 2022-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0002_accountsales_ad_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsales',
            name='ad_fees_currency',
        ),
        migrations.RemoveField(
            model_name='accountsales',
            name='platform_fees_currency',
        ),
        migrations.RemoveField(
            model_name='accountsales',
            name='receipts_currency',
        ),
        migrations.RemoveField(
            model_name='accountsales',
            name='refund_currency',
        ),
        migrations.RemoveField(
            model_name='accountsales',
            name='sale_currency',
        ),
        migrations.AddField(
            model_name='accountsales',
            name='currency_rate',
            field=models.FloatField(blank=True, help_text='汇率值', null=True, verbose_name='汇率值'),
        ),
        migrations.AddField(
            model_name='accountsales',
            name='ori_currency',
            field=models.CharField(blank=True, help_text='原始币种', max_length=10, null=True, verbose_name='原始币种'),
        ),
        migrations.AlterField(
            model_name='accountsales',
            name='cp_cgf_fees',
            field=models.FloatField(blank=True, help_text='CGF费用', null=True, verbose_name='CGF费用'),
        ),
    ]
