# Generated by Django 3.2.4 on 2022-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_auto_20220616_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsales',
            name='sale_income',
            field=models.FloatField(blank=True, help_text='销售收入(原始货币)', null=True, verbose_name='销售收入(原始货币)'),
        ),
    ]
