# Generated by Django 3.2.4 on 2022-06-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_accountsales_sale_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsales',
            name='manager',
            field=models.ForeignKey(help_text='账号负责人', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_sales', to='bonus.manager', verbose_name='账号负责人'),
        ),
    ]
