# Generated by Django 3.2.4 on 2022-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0005_alter_accountsales_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsales',
            name='platform_fees_rmb',
            field=models.FloatField(blank=True, help_text='平台费用 (rmb)', null=True, verbose_name='平台费用 (rmb)'),
        ),
    ]
