# Generated by Django 3.2.4 on 2022-06-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0006_accountsales_platform_fees_rmb'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsales',
            name='ad_fees_rmb',
            field=models.FloatField(blank=True, help_text='广告费(rmb)', null=True, verbose_name='广告费(rmb)'),
        ),
    ]
