# Generated by Django 3.2.4 on 2022-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0008_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, help_text='月份', max_length=10, null=True, verbose_name='月份')),
                ('status', models.BooleanField(default=False, help_text='状态', verbose_name='状态')),
            ],
            options={
                'verbose_name': '统计月份',
                'verbose_name_plural': '统计月份',
                'ordering': ['-id'],
            },
        ),
    ]
