# Generated by Django 3.2.4 on 2022-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0010_auto_20220618_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='platform',
            field=models.CharField(blank=True, help_text='所属平台', max_length=30, null=True, verbose_name='所属平台'),
        ),
    ]
