# Generated by Django 3.2.4 on 2022-06-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0011_basicinfo_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbonus',
            name='ad_fees_currency',
        ),
        migrations.RemoveField(
            model_name='accountbonus',
            name='platform_fees_currency',
        ),
        migrations.RemoveField(
            model_name='accountbonus',
            name='receipts_currency',
        ),
        migrations.RemoveField(
            model_name='accountbonus',
            name='refund_currency',
        ),
        migrations.RemoveField(
            model_name='accountbonus',
            name='sale_currency',
        ),
        migrations.AddField(
            model_name='accountbonus',
            name='ad_fees_rmb',
            field=models.FloatField(blank=True, help_text='广告费(rmb)', null=True, verbose_name='广告费(rmb)'),
        ),
        migrations.AddField(
            model_name='accountbonus',
            name='ad_percent',
            field=models.FloatField(blank=True, help_text='广告费占比', null=True, verbose_name='广告费占比'),
        ),
        migrations.AddField(
            model_name='accountbonus',
            name='currency_rate',
            field=models.FloatField(blank=True, help_text='汇率值', null=True, verbose_name='汇率值'),
        ),
        migrations.AddField(
            model_name='accountbonus',
            name='ori_currency',
            field=models.CharField(blank=True, help_text='原始币种', max_length=10, null=True, verbose_name='原始币种'),
        ),
        migrations.AddField(
            model_name='accountbonus',
            name='platform_fees_rmb',
            field=models.FloatField(blank=True, help_text='平台费用 (rmb)', null=True, verbose_name='平台费用 (rmb)'),
        ),
        migrations.AddField(
            model_name='accountbonus',
            name='sale_income',
            field=models.FloatField(blank=True, help_text='销售收入(原始货币)', null=True, verbose_name='销售收入(原始货币)'),
        ),
        migrations.AlterField(
            model_name='accountbonus',
            name='cp_cgf_fees',
            field=models.FloatField(blank=True, help_text='CGF费用', null=True, verbose_name='CGF费用'),
        ),
    ]
