# Generated by Django 3.2.4 on 2024-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0014_alter_accountbonus_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='site',
            field=models.CharField(blank=True, help_text='站点', max_length=30, null=True, verbose_name='站点'),
        ),
    ]
