# Generated by Django 3.2.4 on 2024-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0015_accounts_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用'),
        ),
    ]
