# Generated by Django 3.2.4 on 2024-09-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0016_accounts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用'),
        ),
    ]
