# Generated by Django 3.2.4 on 2024-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0017_manager_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='ac_type',
            field=models.CharField(blank=True, help_text='账号类型', max_length=10, null=True, verbose_name='账号类型'),
        ),
    ]
