# Generated by Django 3.2.4 on 2024-10-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0018_accounts_ac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='ac_type',
            field=models.CharField(blank=True, default='CHINA', help_text='账号类型', max_length=10, null=True, verbose_name='账号类型'),
        ),
    ]
