# Generated by Django 3.2.4 on 2022-07-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(help_text='商品id', max_length=20, verbose_name='商品id')),
                ('site_id', models.CharField(help_text='站点id', max_length=10, verbose_name='站点id')),
                ('title', models.CharField(help_text='商品名称', max_length=150, verbose_name='商品名称')),
                ('image', models.CharField(blank=True, help_text='主图链接', max_length=200, null=True, verbose_name='主图链接')),
                ('link', models.CharField(blank=True, help_text='商品链接', max_length=200, null=True, verbose_name='商品链接')),
                ('price', models.FloatField(blank=True, help_text='销售定价', null=True, verbose_name='销售定价')),
                ('currency', models.FloatField(blank=True, help_text='币种', max_length=5, null=True, verbose_name='币种')),
                ('total_sold', models.IntegerField(blank=True, default=0, help_text='总销量', null=True, verbose_name='总销量')),
                ('sold_7d', models.IntegerField(blank=True, default=0, help_text='近7天销量', null=True, verbose_name='近7天销量')),
                ('sold_30d', models.IntegerField(blank=True, default=0, help_text='近30天销量', null=True, verbose_name='近30天销量')),
                ('reviews', models.IntegerField(blank=True, default=0, help_text='评论数量', null=True, verbose_name='评论数量')),
                ('rating_average', models.FloatField(blank=True, help_text='评分', null=True, verbose_name='评分')),
                ('start_date', models.DateField(help_text='上架时间', null=True, verbose_name='上架时间')),
                ('listing_status', models.CharField(blank=True, help_text='商品状态', max_length=10, null=True, verbose_name='商品状态')),
                ('health', models.FloatField(blank=True, help_text='健康度', null=True, verbose_name='健康度')),
                ('stock_num', models.IntegerField(blank=True, default=0, help_text='库存数', null=True, verbose_name='库存数')),
                ('ship_type', models.CharField(blank=True, help_text='物流类型', max_length=20, null=True, verbose_name='物流类型')),
                ('is_cbt', models.BooleanField(default=True, help_text='是否大陆卖家', verbose_name='是否大陆卖家')),
                ('is_free_shipping', models.BooleanField(default=True, help_text='是否免运费', verbose_name='是否免运费')),
                ('seller_id', models.CharField(blank=True, help_text='卖家id', max_length=20, null=True, verbose_name='卖家id')),
                ('seller_name', models.CharField(blank=True, help_text='卖家名称', max_length=50, null=True, verbose_name='卖家名称')),
                ('brand', models.CharField(blank=True, help_text='品牌名称', max_length=20, null=True, verbose_name='品牌名称')),
                ('collection', models.BooleanField(default=False, help_text='是否收藏', verbose_name='是否收藏')),
                ('cost', models.FloatField(blank=True, help_text='商品成本', null=True, verbose_name='商品成本')),
                ('profit', models.FloatField(blank=True, help_text='利润', null=True, verbose_name='利润')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(help_text='数据更新时间', null=True, verbose_name='数据更新时间')),
            ],
            options={
                'verbose_name': '在线产品',
                'verbose_name_plural': '在线产品',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ListingTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.FloatField(blank=True, help_text='币种', max_length=5, null=True, verbose_name='币种')),
                ('total_sold', models.IntegerField(blank=True, default=0, help_text='总销量', null=True, verbose_name='总销量')),
                ('today_sold', models.IntegerField(blank=True, default=0, help_text='今天销量', null=True, verbose_name='今天销量')),
                ('reviews', models.IntegerField(blank=True, default=0, help_text='评论数量', null=True, verbose_name='评论数量')),
                ('rating_average', models.FloatField(blank=True, help_text='评分', null=True, verbose_name='评分')),
                ('health', models.FloatField(blank=True, help_text='健康度', null=True, verbose_name='健康度')),
                ('stock_num', models.IntegerField(blank=True, default=0, help_text='库存数', null=True, verbose_name='库存数')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('listing', models.ForeignKey(help_text='在线产品', on_delete=django.db.models.deletion.CASCADE, related_name='listing_track', to='mercado.listing', verbose_name='在线产品')),
            ],
            options={
                'verbose_name': '商品跟踪',
                'verbose_name_plural': '商品跟踪',
                'ordering': ['-create_time'],
            },
        ),
    ]
