# Generated by Django 3.2.4 on 2022-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='api-token', max_length=50, verbose_name='api-token')),
            ],
            options={
                'verbose_name': 'api设置',
                'verbose_name_plural': 'api设置',
            },
        ),
    ]
