# Generated by Django 3.2.4 on 2022-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_apisetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(blank=True, help_text='币种', max_length=5, null=True, verbose_name='币种'),
        ),
    ]
