# Generated by Django 3.2.4 on 2022-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='registration_date',
            field=models.DateField(help_text='注册日期', null=True, verbose_name='注册日期'),
        ),
    ]
