# Generated by Django 3.2.4 on 2022-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_alter_listingtrack_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtrack',
            name='price',
            field=models.FloatField(blank=True, default=0, help_text='销售定价', null=True, verbose_name='销售定价'),
        ),
    ]
