# Generated by Django 3.2.4 on 2022-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_listingtrack_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_id', models.CharField(help_text='类目id', max_length=10, verbose_name='类目id')),
                ('father_id', models.CharField(help_text='父类目id', max_length=10, verbose_name='父类目id')),
                ('site_id', models.CharField(help_text='站点id', max_length=10, verbose_name='站点id')),
                ('name', models.CharField(help_text='类目名称', max_length=100, verbose_name='类目名称')),
                ('t_name', models.CharField(help_text='翻译类目名称', max_length=100, verbose_name='翻译类目名称')),
                ('path_from_root', models.CharField(help_text='类目导航', max_length=200, verbose_name='类目导航')),
                ('total_items', models.IntegerField(blank=True, default=0, help_text='类目产品数量', null=True, verbose_name='类目产品数量')),
                ('has_children', models.BooleanField(default=False, help_text='是否有子类目', verbose_name='是否有子类目')),
                ('collection', models.BooleanField(default=False, help_text='是否收藏', verbose_name='是否收藏')),
                ('update_time', models.DateTimeField(help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '站点类目',
                'verbose_name_plural': '站点类目',
                'ordering': ['id'],
            },
        ),
    ]
