# Generated by Django 3.2.4 on 2022-07-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_auto_20220725_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='has_children',
            field=models.BooleanField(default=True, help_text='是否有子类目', verbose_name='是否有子类目'),
        ),
    ]
