# Generated by Django 3.2.4 on 2022-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_alter_categories_has_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='t_name',
            field=models.CharField(blank=True, help_text='翻译类目名称', max_length=100, null=True, verbose_name='翻译类目名称'),
        ),
    ]
