# Generated by Django 3.2.4 on 2022-07-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0011_alter_categories_t_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransApiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(help_text='appid', max_length=50, verbose_name='appid')),
                ('secretKey', models.CharField(help_text='appid', max_length=50, verbose_name='appid')),
            ],
            options={
                'verbose_name': '百度翻译api设置',
                'verbose_name_plural': '百度翻译api设置',
            },
        ),
    ]
