# Generated by Django 3.2.4 on 2022-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0012_transapisetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transapisetting',
            name='secretKey',
            field=models.CharField(help_text='secretKey', max_length=50, verbose_name='secretKey'),
        ),
    ]
