# Generated by Django 3.2.4 on 2022-07-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0014_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='collection',
        ),
        migrations.AlterField(
            model_name='keywords',
            name='status',
            field=models.CharField(blank=True, help_text='状态', max_length=5, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='t_keyword',
            field=models.CharField(blank=True, help_text='关键词翻译', max_length=50, null=True, verbose_name='关键词翻译'),
        ),
    ]
