# Generated by Django 3.2.4 on 2022-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0015_auto_20220728_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='t_keyword',
            field=models.CharField(blank=True, help_text='关键词翻译', max_length=100, null=True, verbose_name='关键词翻译'),
        ),
    ]
