# Generated by Django 3.2.4 on 2022-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0016_alter_keywords_t_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(help_text='关键词', max_length=100, null=True, verbose_name='关键词'),
        ),
    ]
