# Generated by Django 3.2.4 on 2022-07-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0017_alter_keywords_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='collection',
            field=models.BooleanField(default=False, help_text='是否收藏', verbose_name='是否收藏'),
        ),
        migrations.AddField(
            model_name='seller',
            name='link',
            field=models.CharField(blank=True, help_text='店铺链接', max_length=200, null=True, verbose_name='店铺链接'),
        ),
        migrations.AddField(
            model_name='seller',
            name='sold_60d',
            field=models.IntegerField(blank=True, default=0, help_text='60天销量', null=True, verbose_name='60天销量'),
        ),
        migrations.AddField(
            model_name='seller',
            name='total_items',
            field=models.IntegerField(blank=True, default=0, help_text='listing数量', null=True, verbose_name='listing数量'),
        ),
        migrations.AddField(
            model_name='seller',
            name='update_time',
            field=models.DateTimeField(help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='nickname',
            field=models.CharField(help_text='卖家名称', max_length=50, verbose_name='卖家名称'),
        ),
    ]
