# Generated by Django 3.2.4 on 2022-07-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0018_auto_20220729_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=0, help_text='总订单', null=True, verbose_name='总订单')),
                ('today_sold', models.IntegerField(blank=True, default=0, help_text='今天订单', null=True, verbose_name='今天订单')),
                ('negative', models.FloatField(blank=True, help_text='差评率', null=True, verbose_name='差评率')),
                ('neutral', models.FloatField(blank=True, help_text='中评率', null=True, verbose_name='中评率')),
                ('positive', models.FloatField(blank=True, help_text='好评率', null=True, verbose_name='好评率')),
                ('total_items', models.IntegerField(blank=True, default=0, help_text='listing数量', null=True, verbose_name='listing数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('seller', models.ForeignKey(help_text='卖家', on_delete=django.db.models.deletion.CASCADE, related_name='seller_track', to='mercado.seller', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '卖家跟踪',
                'verbose_name_plural': '卖家跟踪',
                'ordering': ['-create_time'],
            },
        ),
    ]
