# Generated by Django 3.2.4 on 2022-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0020_auto_20220801_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='产品SKU', max_length=30, verbose_name='产品SKU')),
                ('p_name', models.CharField(help_text='产品名称', max_length=80, verbose_name='产品名称')),
                ('label_code', models.CharField(blank=True, help_text='FBM条码', max_length=30, null=True, verbose_name='FBM条码')),
                ('upc', models.CharField(blank=True, help_text='UPC', max_length=30, null=True, verbose_name='UPC')),
                ('item_id', models.CharField(blank=True, help_text='链接编号', max_length=30, null=True, verbose_name='链接编号')),
                ('image', models.ImageField(blank=True, help_text='产品图片', max_length=200, null=True, upload_to='ml_product', verbose_name='产品图片')),
                ('p_status', models.CharField(choices=[('ON_SALE', '在售'), ('OFFLINE', '停售'), ('CLEAN', '清仓中')], default='ON_SALE', help_text='产品状态', max_length=10, verbose_name='产品状态')),
                ('custom_code', models.CharField(blank=True, help_text='海关编码', max_length=20, null=True, verbose_name='海关编码')),
                ('cn_name', models.CharField(blank=True, help_text='中文品名', max_length=30, null=True, verbose_name='中文品名')),
                ('en_name', models.CharField(blank=True, help_text='英文品名', max_length=30, null=True, verbose_name='英文品名')),
                ('brand', models.CharField(blank=True, help_text='品牌', max_length=20, null=True, verbose_name='品牌')),
                ('declared_value', models.FloatField(blank=True, help_text='申报价值USD', max_length=30, null=True, verbose_name='申报价值USD')),
                ('cn_material', models.CharField(blank=True, help_text='中文材质', max_length=30, null=True, verbose_name='中文材质')),
                ('en_material', models.CharField(blank=True, help_text='英文材质', max_length=30, null=True, verbose_name='英文材质')),
                ('use', models.CharField(blank=True, help_text='用途', max_length=50, null=True, verbose_name='用途')),
                ('site', models.CharField(blank=True, help_text='站点', max_length=30, null=True, verbose_name='站点')),
                ('shop', models.CharField(blank=True, help_text='上架店铺', max_length=50, null=True, verbose_name='上架店铺')),
                ('unit_cost', models.FloatField(blank=True, help_text='成本价', null=True, verbose_name='成本价')),
                ('first_ship_cost', models.FloatField(blank=True, help_text='预估头程运费', null=True, verbose_name='预估头程运费')),
                ('length', models.FloatField(blank=True, help_text='长cm', null=True, verbose_name='长cm')),
                ('width', models.FloatField(blank=True, help_text='宽cm', null=True, verbose_name='宽cm')),
                ('heigth', models.FloatField(blank=True, help_text='高cm', null=True, verbose_name='高cm')),
                ('weight', models.FloatField(blank=True, help_text='重量kg', null=True, verbose_name='重量kg')),
                ('buy_url', models.CharField(blank=True, help_text='产品采购链接', max_length=500, null=True, verbose_name='产品采购链接')),
                ('sale_url', models.CharField(blank=True, help_text='销售链接', max_length=500, null=True, verbose_name='销售链接')),
                ('refer_url', models.CharField(blank=True, help_text='参考链接', max_length=500, null=True, verbose_name='参考链接')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'ML产品库',
                'verbose_name_plural': 'ML产品库',
                'ordering': ['-create_time'],
            },
        ),
    ]
