# Generated by Django 3.2.4 on 2022-11-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0023_alter_shop_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstock',
            name='trans_qty',
            field=models.IntegerField(default=0, help_text='中转仓数量', verbose_name='中转仓数量'),
        ),
        migrations.AlterField(
            model_name='shopstock',
            name='first_ship_cost',
            field=models.FloatField(default=0, help_text='均摊头程运费', null=True, verbose_name='均摊头程运费'),
        ),
        migrations.AlterField(
            model_name='shopstock',
            name='unit_cost',
            field=models.FloatField(default=0, help_text='均摊成本价', null=True, verbose_name='均摊成本价'),
        ),
    ]
