# Generated by Django 3.2.4 on 2022-11-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0024_auto_20221119_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_number', models.CharField(blank=True, help_text='运单编号', max_length=30, null=True, verbose_name='运单编号')),
                ('batch', models.CharField(blank=True, help_text='批次号', max_length=30, null=True, verbose_name='批次号')),
                ('p_status', models.CharField(choices=[('PREPARING', '备货中'), ('SHIPPED', '已发货'), ('BOOKED', '已预约'), ('FINISHED', '已完成'), ('ERROR', '异常')], default='PREPARING', help_text='产品状态', max_length=10, verbose_name='产品状态')),
                ('shop', models.CharField(blank=True, help_text='目标店铺', max_length=30, null=True, verbose_name='目标店铺')),
                ('target', models.CharField(blank=True, help_text='目标入仓FBM/中转仓', max_length=30, null=True, verbose_name='目标入仓FBM/中转仓')),
                ('envio_number', models.CharField(blank=True, help_text='Envio号', max_length=30, null=True, verbose_name='Envio号')),
                ('target_FBM', models.CharField(blank=True, help_text='FBM仓库', max_length=30, null=True, verbose_name='FBM仓库')),
                ('ship_type', models.CharField(blank=True, help_text='运单类型', max_length=10, null=True, verbose_name='运单类型')),
                ('shipping_fee', models.FloatField(default=0, help_text='运费', null=True, verbose_name='运费')),
                ('extra_fee', models.FloatField(default=0, help_text='额外费用', null=True, verbose_name='额外费用')),
                ('carrier', models.CharField(blank=True, help_text='承运商', max_length=30, null=True, verbose_name='承运商')),
                ('end_date', models.DateField(help_text='物流截单日期', null=True, verbose_name='物流截单日期')),
                ('ship_date', models.DateField(help_text='航班日期', null=True, verbose_name='航班日期')),
                ('book_date', models.DateTimeField(help_text='FBM预约日期', null=True, verbose_name='FBM预约日期')),
                ('total_box', models.IntegerField(default=0, help_text='总箱数', verbose_name='总箱数')),
                ('total_qty', models.IntegerField(default=0, help_text='总数量', verbose_name='总数量')),
                ('weight', models.FloatField(blank=True, help_text='总重量kg', null=True, verbose_name='总重量kg')),
                ('cbm', models.FloatField(blank=True, help_text='总体积cbm', null=True, verbose_name='总体积cbm')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '头程运单',
                'verbose_name_plural': '头程运单',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(help_text='箱号', max_length=30, verbose_name='箱号')),
                ('s_type', models.CharField(help_text='发货类型', max_length=10, verbose_name='发货类型')),
                ('sku', models.CharField(help_text='产品SKU', max_length=30, verbose_name='产品SKU')),
                ('p_name', models.CharField(help_text='产品名称', max_length=80, verbose_name='产品名称')),
                ('label_code', models.CharField(blank=True, help_text='FBM条码', max_length=30, null=True, verbose_name='FBM条码')),
                ('upc', models.CharField(blank=True, help_text='UPC', max_length=30, null=True, verbose_name='UPC')),
                ('item_id', models.CharField(blank=True, help_text='链接编号', max_length=30, null=True, verbose_name='链接编号')),
                ('image', models.ImageField(blank=True, help_text='产品图片', max_length=200, null=True, upload_to='ml_product', verbose_name='产品图片')),
                ('custom_code', models.CharField(blank=True, help_text='海关编码', max_length=20, null=True, verbose_name='海关编码')),
                ('cn_name', models.CharField(blank=True, help_text='中文品名', max_length=30, null=True, verbose_name='中文品名')),
                ('en_name', models.CharField(blank=True, help_text='英文品名', max_length=30, null=True, verbose_name='英文品名')),
                ('brand', models.CharField(blank=True, help_text='品牌', max_length=20, null=True, verbose_name='品牌')),
                ('declared_value', models.FloatField(blank=True, help_text='申报价值USD', max_length=30, null=True, verbose_name='申报价值USD')),
                ('cn_material', models.CharField(blank=True, help_text='中文材质', max_length=30, null=True, verbose_name='中文材质')),
                ('en_material', models.CharField(blank=True, help_text='英文材质', max_length=30, null=True, verbose_name='英文材质')),
                ('use', models.CharField(blank=True, help_text='用途', max_length=50, null=True, verbose_name='用途')),
                ('unit_cost', models.FloatField(default=0, help_text='成本价', null=True, verbose_name='成本价')),
                ('avg_ship_fee', models.FloatField(default=0, help_text='单个分摊运费', null=True, verbose_name='单个分摊运费')),
                ('qty', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('length', models.FloatField(blank=True, help_text='长cm', null=True, verbose_name='长cm')),
                ('width', models.FloatField(blank=True, help_text='宽cm', null=True, verbose_name='宽cm')),
                ('heigth', models.FloatField(blank=True, help_text='高cm', null=True, verbose_name='高cm')),
                ('weight', models.FloatField(blank=True, help_text='重量kg', null=True, verbose_name='重量kg')),
                ('note', models.CharField(blank=True, help_text='短备注', max_length=300, null=True, verbose_name='短备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('ship', models.ForeignKey(help_text='所属运单', on_delete=django.db.models.deletion.CASCADE, related_name='ship_shipDetail', to='mercado.ship', verbose_name='所属运单')),
            ],
            options={
                'verbose_name': '运单详情',
                'verbose_name_plural': '运单详情',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShipBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(help_text='箱号', max_length=30, verbose_name='箱号')),
                ('carrier_box_number', models.CharField(help_text='物流商箱唛号', max_length=30, verbose_name='物流商箱唛号')),
                ('item_qty', models.IntegerField(default=0, help_text='箱内产品数量', verbose_name='箱内产品数量')),
                ('length', models.FloatField(blank=True, help_text='长cm', null=True, verbose_name='长cm')),
                ('width', models.FloatField(blank=True, help_text='宽cm', null=True, verbose_name='宽cm')),
                ('heigth', models.FloatField(blank=True, help_text='高cm', null=True, verbose_name='高cm')),
                ('weight', models.FloatField(blank=True, help_text='重量kg', null=True, verbose_name='重量kg')),
                ('cbm', models.FloatField(blank=True, help_text='体积cbm', null=True, verbose_name='体积cbm')),
                ('size_weight', models.FloatField(blank=True, help_text='体积重kg', null=True, verbose_name='体积重kg')),
                ('note', models.CharField(blank=True, help_text='短备注', max_length=300, null=True, verbose_name='短备注')),
                ('ship', models.ForeignKey(help_text='所属运单', on_delete=django.db.models.deletion.CASCADE, related_name='ship_shipBox', to='mercado.ship', verbose_name='所属运单')),
            ],
            options={
                'verbose_name': '包装箱',
                'verbose_name_plural': '包装箱',
                'ordering': ['id'],
            },
        ),
    ]
