# Generated by Django 3.2.4 on 2022-11-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0025_ship_shipbox_shipdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='p_status',
            new_name='s_status',
        ),
    ]
