# Generated by Django 3.2.4 on 2022-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0026_rename_p_status_ship_s_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='book_date',
            field=models.DateField(help_text='FBM预约日期', null=True, verbose_name='FBM预约日期'),
        ),
    ]
