# Generated by Django 3.2.4 on 2022-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0028_auto_20221120_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_num', models.IntegerField(default=1, help_text='排序号', verbose_name='排序号')),
                ('name', models.CharField(help_text='物流名称', max_length=30, verbose_name='物流名称')),
            ],
            options={
                'verbose_name': '包装箱',
                'verbose_name_plural': '包装箱',
                'ordering': ['id'],
            },
        ),
    ]
