# Generated by Django 3.2.4 on 2022-11-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0029_carrier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['id'], 'verbose_name': '物流商', 'verbose_name_plural': '物流商'},
        ),
    ]
