# Generated by Django 3.2.4 on 2022-11-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0031_alter_shipbox_carrier_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstock',
            name='p_status',
            field=models.CharField(choices=[('NORMAL', '普通'), ('HOT_SALE', '热卖'), ('OFFLINE', '停售'), ('CLEAN', '清仓中')], default='NORMAL', help_text='产品状态', max_length=10, verbose_name='产品状态'),
        ),
    ]
