# Generated by Django 3.2.4 on 2022-11-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0032_alter_shopstock_p_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_shop', models.CharField(blank=True, help_text='上架店铺', max_length=60, null=True, verbose_name='上架店铺')),
                ('sku', models.CharField(help_text='产品SKU', max_length=30, verbose_name='产品SKU')),
                ('p_name', models.CharField(help_text='产品名称', max_length=80, verbose_name='产品名称')),
                ('label_code', models.CharField(blank=True, help_text='FBM条码', max_length=30, null=True, verbose_name='FBM条码')),
                ('upc', models.CharField(blank=True, help_text='UPC', max_length=30, null=True, verbose_name='UPC')),
                ('item_id', models.CharField(blank=True, help_text='链接编号', max_length=30, null=True, verbose_name='链接编号')),
                ('image', models.ImageField(blank=True, help_text='产品图片', max_length=200, null=True, upload_to='ml_product', verbose_name='产品图片')),
                ('qty', models.IntegerField(default=0, help_text='库存数量', verbose_name='库存数量')),
                ('unit_cost', models.FloatField(default=0, help_text='均摊成本价', null=True, verbose_name='均摊成本价')),
                ('first_ship_cost', models.FloatField(default=0, help_text='均摊头程运费', null=True, verbose_name='均摊头程运费')),
                ('s_number', models.CharField(blank=True, help_text='运单编号', max_length=30, null=True, verbose_name='运单编号')),
                ('batch', models.CharField(blank=True, help_text='批次号', max_length=30, null=True, verbose_name='批次号')),
                ('box_number', models.CharField(help_text='箱号', max_length=30, verbose_name='箱号')),
                ('carrier_box_number', models.CharField(blank=True, help_text='物流商箱唛号', max_length=30, null=True, verbose_name='物流商箱唛号')),
                ('box_length', models.FloatField(blank=True, help_text='长cm', null=True, verbose_name='长cm')),
                ('box_width', models.FloatField(blank=True, help_text='宽cm', null=True, verbose_name='宽cm')),
                ('box_heigth', models.FloatField(blank=True, help_text='高cm', null=True, verbose_name='高cm')),
                ('box_weight', models.FloatField(blank=True, help_text='重量kg', null=True, verbose_name='重量kg')),
                ('box_cbm', models.FloatField(blank=True, help_text='体积cbm', null=True, verbose_name='体积cbm')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('arrived_date', models.DateField(blank=True, help_text='到仓日期', null=True, verbose_name='到仓日期')),
                ('stock_days', models.IntegerField(default=0, help_text='库龄', verbose_name='库龄')),
                ('is_out', models.BooleanField(default=True, help_text='是否已出仓', verbose_name='是否已出仓')),
                ('shop', models.ForeignKey(help_text='所属中转仓', on_delete=django.db.models.deletion.CASCADE, related_name='shop_trans_stock', to='mercado.shop', verbose_name='所属中转仓')),
            ],
            options={
                'verbose_name': '中转仓库存',
                'verbose_name_plural': '中转仓库存',
                'ordering': ['id'],
            },
        ),
    ]
