# Generated by Django 3.2.4 on 2022-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0034_alter_transstock_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetail',
            name='target_FBM',
            field=models.CharField(blank=True, help_text='目标FBM仓库', max_length=30, null=True, verbose_name='目标FBM仓库'),
        ),
    ]
