# Generated by Django 3.2.4 on 2022-11-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0035_shipdetail_target_fbm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='target_FBM',
        ),
        migrations.AddField(
            model_name='ship',
            name='send_from',
            field=models.CharField(blank=True, help_text='从哪发', max_length=30, null=True, verbose_name='从哪发'),
        ),
    ]
