# Generated by Django 3.2.4 on 2022-11-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0036_auto_20221125_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_num', models.IntegerField(default=1, help_text='排序号', verbose_name='排序号')),
                ('site_code', models.CharField(help_text='站点编号', max_length=30, verbose_name='站点编号')),
                ('name', models.CharField(help_text='站点名称', max_length=30, verbose_name='站点名称')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'ordering': ['od_num'],
            },
        ),
    ]
