# Generated by Django 3.2.4 on 2022-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0037_mlsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='fbm_warehouse',
            field=models.CharField(blank=True, help_text='fbm仓库', max_length=30, null=True, verbose_name='fbm仓库'),
        ),
    ]
