# Generated by Django 3.2.4 on 2022-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0038_ship_fbm_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBMWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, help_text='国家', max_length=30, null=True, verbose_name='国家')),
                ('w_code', models.CharField(help_text='仓库代码', max_length=30, verbose_name='仓库代码')),
                ('name', models.CharField(blank=True, help_text='仓库名称', max_length=30, null=True, verbose_name='仓库名称')),
                ('address', models.CharField(blank=True, help_text='仓库地址', max_length=30, null=True, verbose_name='仓库地址')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'FBM仓库',
                'verbose_name_plural': 'FBM仓库',
                'ordering': ['create_time'],
            },
        ),
    ]
