# Generated by Django 3.2.4 on 2022-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0039_fbmwarehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbmwarehouse',
            name='address',
            field=models.CharField(blank=True, help_text='仓库地址', max_length=300, null=True, verbose_name='仓库地址'),
        ),
        migrations.AlterField(
            model_name='fbmwarehouse',
            name='name',
            field=models.CharField(blank=True, help_text='仓库名称', max_length=100, null=True, verbose_name='仓库名称'),
        ),
    ]
