# Generated by Django 3.2.4 on 2022-11-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0040_auto_20221128_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='currency',
            field=models.CharField(blank=True, help_text='币种', max_length=10, null=True, verbose_name='币种'),
        ),
        migrations.CreateModel(
            name='MLOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, help_text='订单编号', max_length=30, null=True, verbose_name='订单编号')),
                ('order_status', models.CharField(blank=True, help_text='订单状态', max_length=10, null=True, verbose_name='订单状态')),
                ('order_time', models.DateTimeField(blank=True, help_text='订单时间', null=True, verbose_name='订单时间')),
                ('order_time_bj', models.DateTimeField(blank=True, help_text='订单北京时间', null=True, verbose_name='订单北京时间')),
                ('qty', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('currency', models.CharField(blank=True, help_text='币种', max_length=5, null=True, verbose_name='币种')),
                ('ex_rate', models.FloatField(blank=True, default=0, help_text='汇率', null=True, verbose_name='汇率')),
                ('price', models.FloatField(blank=True, default=0, help_text='销售价', null=True, verbose_name='销售价')),
                ('fees', models.FloatField(blank=True, default=0, help_text='佣金', null=True, verbose_name='佣金')),
                ('postage', models.FloatField(blank=True, default=0, help_text='邮费', null=True, verbose_name='邮费')),
                ('receive_fund', models.FloatField(blank=True, default=0, help_text='收入资金', null=True, verbose_name='收入资金')),
                ('profit', models.FloatField(blank=True, default=0, help_text='利润rmb', null=True, verbose_name='利润rmb')),
                ('is_ad', models.BooleanField(default=False, help_text='是否广告卖出', verbose_name='是否广告卖出')),
                ('sku', models.CharField(help_text='产品SKU', max_length=30, verbose_name='产品SKU')),
                ('p_name', models.CharField(help_text='产品名称', max_length=80, verbose_name='产品名称')),
                ('item_id', models.CharField(blank=True, help_text='链接编号', max_length=30, null=True, verbose_name='链接编号')),
                ('image', models.ImageField(blank=True, help_text='产品图片', max_length=200, null=True, upload_to='ml_product', verbose_name='产品图片')),
                ('unit_cost', models.FloatField(default=0, help_text='均摊成本价', null=True, verbose_name='均摊成本价')),
                ('first_ship_cost', models.FloatField(default=0, help_text='均摊头程运费', null=True, verbose_name='均摊头程运费')),
                ('buyer_name', models.CharField(blank=True, help_text='买家姓名', max_length=30, null=True, verbose_name='买家姓名')),
                ('buyer_address', models.CharField(blank=True, help_text='买家街道', max_length=500, null=True, verbose_name='买家街道')),
                ('buyer_city', models.CharField(blank=True, help_text='买家城市', max_length=50, null=True, verbose_name='买家城市')),
                ('buyer_state', models.CharField(blank=True, help_text='买家州', max_length=30, null=True, verbose_name='买家州')),
                ('buyer_postcode', models.CharField(blank=True, help_text='买家邮编', max_length=20, null=True, verbose_name='买家邮编')),
                ('buyer_country', models.CharField(blank=True, help_text='买家国家', max_length=20, null=True, verbose_name='买家国家')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('shop', models.ForeignKey(help_text='所属店铺', on_delete=django.db.models.deletion.CASCADE, related_name='shop_order', to='mercado.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'ordering': ['create_time'],
            },
        ),
    ]
