# Generated by Django 3.2.4 on 2022-11-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0041_auto_20221129_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlorder',
            name='currency',
        ),
    ]
