# Generated by Django 3.2.4 on 2022-11-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0042_remove_mlorder_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='currency',
        ),
    ]
