# Generated by Django 3.2.4 on 2022-11-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0044_auto_20221129_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='币种', max_length=10, verbose_name='币种')),
                ('value', models.FloatField(blank=True, default=0, help_text='汇率', null=True, verbose_name='汇率')),
                ('update_time', models.DateTimeField(blank=True, help_text='更新时间', null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
                'ordering': ['id'],
            },
        ),
    ]
