# Generated by Django 3.2.4 on 2022-11-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0045_exrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlorder',
            name='buyer_name',
            field=models.CharField(blank=True, help_text='买家姓名', max_length=100, null=True, verbose_name='买家姓名'),
        ),
    ]
