# Generated by Django 3.2.4 on 2022-11-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0046_alter_mlorder_buyer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transstock',
            name='stock_days',
        ),
    ]
