# Generated by Django 3.2.4 on 2022-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0047_remove_transstock_stock_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlorder',
            name='profit_rate',
            field=models.FloatField(blank=True, default=0, help_text='毛利率', null=True, verbose_name='毛利率'),
        ),
        migrations.AddField(
            model_name='shopstock',
            name='avg_profit',
            field=models.FloatField(blank=True, help_text='平均毛利润', null=True, verbose_name='平均毛利润'),
        ),
        migrations.AddField(
            model_name='shopstock',
            name='avg_profit_rate',
            field=models.FloatField(blank=True, help_text='平均毛利率', null=True, verbose_name='平均毛利率'),
        ),
        migrations.AddField(
            model_name='shopstock',
            name='refund_rate',
            field=models.FloatField(blank=True, help_text='退款率', null=True, verbose_name='退款率'),
        ),
    ]
