# Generated by Django 3.2.4 on 2022-11-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0048_auto_20221130_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='tag_color',
            field=models.CharField(blank=True, help_text='标签颜色', max_length=20, null=True, verbose_name='标签颜色'),
        ),
        migrations.AddField(
            model_name='ship',
            name='tag_name',
            field=models.CharField(blank=True, help_text='标签名称', max_length=100, null=True, verbose_name='标签名称'),
        ),
    ]
