# Generated by Django 3.2.4 on 2022-12-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0049_auto_20221130_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, help_text='币种', max_length=10, null=True, verbose_name='币种')),
                ('income', models.FloatField(default=0, help_text='外汇收入金额', null=True, verbose_name='外汇收入金额')),
                ('wd_date', models.DateField(blank=True, help_text='提现日期', null=True, verbose_name='提现日期')),
                ('rec_date', models.DateField(blank=True, help_text='提现到账日期', null=True, verbose_name='提现到账日期')),
                ('exchange', models.FloatField(default=0, help_text='结汇金额', null=True, verbose_name='结汇金额')),
                ('income_rmb', models.FloatField(default=0, help_text='结汇rmb', null=True, verbose_name='结汇rmb')),
                ('exc_date', models.DateField(blank=True, help_text='结汇日期', null=True, verbose_name='结汇日期')),
                ('f_type', models.CharField(blank=True, help_text='资金类型', max_length=10, null=True, verbose_name='资金类型')),
                ('is_received', models.BooleanField(default=False, help_text='外汇是否收到', verbose_name='外汇是否收到')),
                ('shop', models.ForeignKey(help_text='所属店铺', on_delete=django.db.models.deletion.CASCADE, related_name='shop_finance', to='mercado.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '财务管理',
                'verbose_name_plural': '财务管理',
                'ordering': ['id'],
            },
        ),
    ]
