# Generated by Django 3.2.4 on 2022-12-01 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0050_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
