# Generated by Django 3.2.4 on 2022-12-08 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0051_finance_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='包材名称', max_length=80, verbose_name='包材名称')),
                ('size', models.CharField(help_text='尺寸', max_length=80, verbose_name='尺寸')),
                ('weight', models.FloatField(blank=True, default=0, help_text='重量g', null=True, verbose_name='重量g')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '包材管理',
                'verbose_name_plural': '包材管理',
                'ordering': ['create_time'],
            },
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='buy_url2',
            field=models.CharField(blank=True, help_text='产品采购链接2', max_length=500, null=True, verbose_name='产品采购链接2'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='buy_url3',
            field=models.CharField(blank=True, help_text='产品采购链接3', max_length=500, null=True, verbose_name='产品采购链接3'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='buy_url4',
            field=models.CharField(blank=True, help_text='产品采购链接4', max_length=500, null=True, verbose_name='产品采购链接4'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='buy_url5',
            field=models.CharField(blank=True, help_text='产品采购链接5', max_length=500, null=True, verbose_name='产品采购链接5'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='is_checked',
            field=models.BooleanField(default=False, help_text='是否核对', null=True, verbose_name='是否核对'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='label_option',
            field=models.CharField(blank=True, help_text='链接选项', max_length=50, null=True, verbose_name='链接选项'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='label_title',
            field=models.CharField(blank=True, help_text='链接标题', max_length=100, null=True, verbose_name='链接标题'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='packing_id',
            field=models.IntegerField(blank=True, help_text='包材id', null=True, verbose_name='包材id'),
        ),
        migrations.AddField(
            model_name='shipdetail',
            name='packing_name',
            field=models.CharField(blank=True, help_text='包材名称', max_length=80, null=True, verbose_name='包材名称'),
        ),
        migrations.AddField(
            model_name='shipdetail',
            name='packing_size',
            field=models.CharField(blank=True, help_text='包材尺寸', max_length=80, null=True, verbose_name='包材尺寸'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_color',
            field=models.CharField(blank=True, help_text='店铺名称颜色', max_length=20, null=True, verbose_name='店铺名称颜色'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(help_text='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shop', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
