# Generated by Django 3.2.4 on 2022-12-09 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0052_auto_20221208_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shop', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
