# Generated by Django 3.2.4 on 2022-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0053_alter_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='shop_color',
            field=models.CharField(blank=True, help_text='店铺颜色', max_length=30, null=True, verbose_name='店铺颜色'),
        ),
    ]
