# Generated by Django 3.2.4 on 2022-12-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0055_transstock_shop_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transstock',
            name='shop_color',
        ),
    ]
