# Generated by Django 3.2.4 on 2022-12-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0057_remove_ship_shop_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='products_cost',
            field=models.FloatField(default=0, help_text='货品成本', null=True, verbose_name='货品成本'),
        ),
    ]
