# Generated by Django 3.2.4 on 2022-12-15 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0058_ship_products_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLOperateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_module', models.CharField(blank=True, help_text='操作模块', max_length=10, null=True, verbose_name='操作模块')),
                ('op_type', models.CharField(blank=True, help_text='操作类型', max_length=10, null=True, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, help_text='目标类型', max_length=10, null=True, verbose_name='目标类型')),
                ('target_id', models.IntegerField(default=0, help_text='目标id', verbose_name='目标id')),
                ('desc', models.CharField(blank=True, help_text='操作描述', max_length=300, null=True, verbose_name='操作描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='操作时间', verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, help_text='操作人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mlop_log', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['create_time'],
            },
        ),
    ]
