# Generated by Django 3.2.4 on 2022-12-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0059_mloperatelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mloperatelog',
            options={'ordering': ['-create_time'], 'verbose_name': '操作日志', 'verbose_name_plural': '操作日志'},
        ),
    ]
