# Generated by Django 3.2.4 on 2023-01-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0064_transstock_out_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='订单数量', verbose_name='订单数量')),
                ('amount', models.FloatField(default=0.0, help_text='销售额', verbose_name='销售额')),
                ('calc_date', models.DateField(blank=True, help_text='统计日期', null=True, verbose_name='统计日期')),
                ('shop', models.ForeignKey(help_text='店铺', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_report', to='mercado.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '统计店铺每天销量',
                'verbose_name_plural': '统计店铺每天销量',
                'ordering': ['-calc_date'],
            },
        ),
    ]
