# Generated by Django 3.2.4 on 2023-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0066_shopreport_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetail',
            name='plan_qty',
            field=models.IntegerField(default=0, help_text='后台计划数量', verbose_name='后台计划数量'),
        ),
    ]
