# Generated by Django 3.2.4 on 2023-02-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0069_alter_purchasemanage_p_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemanage',
            name='buy_qty',
            field=models.IntegerField(blank=True, default=0, help_text='采购数量', null=True, verbose_name='采购数量'),
        ),
        migrations.AlterField(
            model_name='purchasemanage',
            name='need_qty',
            field=models.IntegerField(blank=True, default=0, help_text='需求数量', null=True, verbose_name='需求数量'),
        ),
        migrations.AlterField(
            model_name='purchasemanage',
            name='rec_qty',
            field=models.IntegerField(blank=True, default=0, help_text='收货数量', null=True, verbose_name='收货数量'),
        ),
        migrations.AlterField(
            model_name='purchasemanage',
            name='used_batch',
            field=models.CharField(blank=True, help_text='使用批次', max_length=30, null=True, verbose_name='使用批次'),
        ),
        migrations.AlterField(
            model_name='purchasemanage',
            name='used_qty',
            field=models.IntegerField(blank=True, default=0, help_text='出库数量', null=True, verbose_name='出库数量'),
        ),
    ]
