# Generated by Django 3.2.4 on 2023-02-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0070_auto_20230215_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemanage',
            name='from_batch',
            field=models.CharField(blank=True, help_text='源批次', max_length=30, null=True, verbose_name='源批次'),
        ),
    ]
