# Generated by Django 3.2.4 on 2023-02-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0071_purchasemanage_from_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemanage',
            name='pack_qty',
            field=models.IntegerField(blank=True, default=0, help_text='打包数量', null=True, verbose_name='打包数量'),
        ),
    ]
