# Generated by Django 3.2.4 on 2023-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0073_auto_20230217_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemanage',
            name='is_qc',
            field=models.BooleanField(default=False, help_text='是否质检', verbose_name='是否质检'),
        ),
    ]
