# Generated by Django 3.2.4 on 2023-02-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0074_purchasemanage_is_qc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipItemRemove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(help_text='遗弃类型', max_length=10, verbose_name='遗弃类型')),
                ('sku', models.CharField(help_text='产品SKU', max_length=30, verbose_name='产品SKU')),
                ('p_name', models.CharField(help_text='产品名称', max_length=80, verbose_name='产品名称')),
                ('item_id', models.CharField(blank=True, help_text='链接编号', max_length=30, null=True, verbose_name='链接编号')),
                ('image', models.ImageField(blank=True, help_text='产品图片', max_length=200, null=True, upload_to='ml_product', verbose_name='产品图片')),
                ('plan_qty', models.IntegerField(blank=True, default=0, help_text='计划数量', null=True, verbose_name='计划数量')),
                ('send_qty', models.IntegerField(blank=True, default=0, help_text='发货数量', null=True, verbose_name='发货数量')),
                ('note', models.CharField(blank=True, help_text='移除原因', max_length=300, null=True, verbose_name='移除原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('ship', models.ForeignKey(help_text='所属运单', on_delete=django.db.models.deletion.CASCADE, related_name='ship_itemRemove', to='mercado.ship', verbose_name='所属运单')),
            ],
            options={
                'verbose_name': '遗弃清单',
                'verbose_name_plural': '遗弃清单',
                'ordering': ['create_time'],
            },
        ),
    ]
