# Generated by Django 3.2.4 on 2023-03-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0075_shipitemremove'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='quota',
            field=models.FloatField(blank=True, help_text='店铺额度', null=True, verbose_name='店铺额度'),
        ),
    ]
