# Generated by Django 3.2.4 on 2023-03-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0076_shop_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_type', models.CharField(help_text='附件类型', max_length=10, verbose_name='附件类型')),
                ('name', models.CharField(blank=True, help_text='附件名称', max_length=50, null=True, verbose_name='附件名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('ship', models.ForeignKey(help_text='所属运单', on_delete=django.db.models.deletion.CASCADE, related_name='ship_attachment', to='mercado.ship', verbose_name='所属运单')),
            ],
            options={
                'verbose_name': '运单附件',
                'verbose_name_plural': '运单附件',
                'ordering': ['id'],
            },
        ),
    ]
