# Generated by Django 3.2.4 on 2023-03-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0077_shipattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipattachment',
            name='name',
            field=models.CharField(blank=True, help_text='附件名称', max_length=100, null=True, verbose_name='附件名称'),
        ),
    ]
