# Generated by Django 3.2.4 on 2023-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0078_alter_shipattachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='logi_fee_clear',
            field=models.BooleanField(default=False, help_text='物流费是否结算', verbose_name='物流费是否结算'),
        ),
    ]
