# Generated by Django 3.2.4 on 2023-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0079_ship_logi_fee_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='sent_time',
            field=models.DateTimeField(blank=True, help_text='发货时间', null=True, verbose_name='发货时间'),
        ),
    ]
