# Generated by Django 3.2.4 on 2023-03-12 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0080_ship_sent_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='upc号码', max_length=50, null=True, verbose_name='upc号码')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='生成时间', verbose_name='生成时间')),
                ('use_time', models.DateTimeField(blank=True, help_text='使用时间', null=True, verbose_name='使用时间')),
                ('is_used', models.BooleanField(default=True, help_text='是否使用', verbose_name='是否使用')),
                ('user', models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_upc', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'UPC号码池',
                'verbose_name_plural': 'UPC号码池',
                'ordering': ['-use_time'],
            },
        ),
    ]
