# Generated by Django 3.2.4 on 2023-03-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0082_alter_upc_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_days', models.IntegerField(default=0, help_text='30天销量', verbose_name='30天销量')),
                ('sea_days', models.IntegerField(default=0, help_text='15天销量', verbose_name='15天销量')),
                ('fly_batch_period', models.IntegerField(default=0, help_text='7天销量', verbose_name='7天销量')),
                ('sea_batch_period', models.IntegerField(default=0, help_text='fbm库存数量', verbose_name='fbm库存数量')),
                ('is_include_trans', models.BooleanField(default=True, help_text='是否包含中转仓数量', verbose_name='是否包含中转仓数量')),
            ],
            options={
                'verbose_name': '补货推荐设置',
                'verbose_name_plural': '补货推荐设置',
                'ordering': ['fly_days'],
            },
        ),
        migrations.CreateModel(
            name='RefillRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='产品SKU', max_length=30, verbose_name='产品SKU')),
                ('p_name', models.CharField(help_text='产品名称', max_length=80, verbose_name='产品名称')),
                ('item_id', models.CharField(blank=True, help_text='链接编号', max_length=30, null=True, verbose_name='链接编号')),
                ('is_new', models.BooleanField(default=False, help_text='是否新品', verbose_name='是否新品')),
                ('first_list_date', models.DateTimeField(blank=True, help_text='首次上架时间', null=True, verbose_name='首次上架时间')),
                ('trend', models.CharField(blank=True, help_text='销量趋势', max_length=10, null=True, verbose_name='销量趋势')),
                ('all_sold', models.IntegerField(default=0, help_text='总销量', verbose_name='总销量')),
                ('days30_sold', models.IntegerField(default=0, help_text='30天销量', verbose_name='30天销量')),
                ('days15_sold', models.IntegerField(default=0, help_text='15天销量', verbose_name='15天销量')),
                ('days7_sold', models.IntegerField(default=0, help_text='7天销量', verbose_name='7天销量')),
                ('fbm_qty', models.IntegerField(default=0, help_text='fbm库存数量', verbose_name='fbm库存数量')),
                ('onway_qty', models.IntegerField(default=0, help_text='在途数量', verbose_name='在途数量')),
                ('trans_qty', models.IntegerField(default=0, help_text='中转仓数量', verbose_name='中转仓数量')),
                ('trans_onway_qty', models.IntegerField(default=0, help_text='中转在途数量', verbose_name='中转在途数量')),
                ('prepare_qty', models.IntegerField(default=0, help_text='备货中数量', verbose_name='备货中数量')),
                ('own_qty', models.IntegerField(default=0, help_text='现货数量', verbose_name='现货数量')),
                ('avg_sale', models.FloatField(default=0.0, help_text='日均销量', verbose_name='日均销量')),
                ('keep_days', models.IntegerField(default=0, help_text='库存维持天数', verbose_name='库存维持天数')),
                ('min_send', models.IntegerField(default=0, help_text='最低发货数量', verbose_name='最低发货数量')),
                ('full_send', models.IntegerField(default=0, help_text='完整周期发货数量', verbose_name='完整周期发货数量')),
                ('create_time', models.DateTimeField(blank=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('shop', models.ForeignKey(help_text='店铺', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_refill', to='mercado.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '补货推荐',
                'verbose_name_plural': '补货推荐',
                'ordering': ['item_id'],
            },
        ),
    ]
