# Generated by Django 3.2.4 on 2023-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0083_refillrecommend_refillsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillsettings',
            name='fly_batch_period',
            field=models.IntegerField(default=0, help_text='空运批次周期', verbose_name='空运批次周期'),
        ),
        migrations.AlterField(
            model_name='refillsettings',
            name='fly_days',
            field=models.IntegerField(default=0, help_text='空运物流及上架时间', verbose_name='空运物流及上架时间'),
        ),
        migrations.AlterField(
            model_name='refillsettings',
            name='sea_batch_period',
            field=models.IntegerField(default=0, help_text='海运批次周期', verbose_name='海运批次周期'),
        ),
        migrations.AlterField(
            model_name='refillsettings',
            name='sea_days',
            field=models.IntegerField(default=0, help_text='海运物流及上架时间', verbose_name='海运物流及上架时间'),
        ),
    ]
