# Generated by Django 3.2.4 on 2023-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0084_auto_20230321_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refillrecommend',
            name='first_list_date',
        ),
        migrations.AddField(
            model_name='refillrecommend',
            name='first_list_days',
            field=models.IntegerField(default=0, help_text='首次上架天数', verbose_name='首次上架天数'),
        ),
    ]
