# Generated by Django 3.2.4 on 2023-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0087_refillrecommend_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillrecommend',
            name='advice',
            field=models.CharField(blank=True, help_text='建议注释', max_length=50, null=True, verbose_name='建议注释'),
        ),
    ]
