# Generated by Django 3.2.4 on 2023-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0089_auto_20230907_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipitemremove',
            name='belong_shop',
            field=models.CharField(blank=True, help_text='产品所属店铺', max_length=30, null=True, verbose_name='产品所属店铺'),
        ),
    ]
