# Generated by Django 3.2.4 on 2023-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0090_shipitemremove_belong_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlproduct',
            name='is_elec',
            field=models.BooleanField(default=False, help_text='是否带电', null=True, verbose_name='是否带电'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='is_magnet',
            field=models.BooleanField(default=False, help_text='是否带磁', null=True, verbose_name='是否带磁'),
        ),
        migrations.AddField(
            model_name='mlproduct',
            name='is_water',
            field=models.BooleanField(default=False, help_text='是否带液体', null=True, verbose_name='是否带液体'),
        ),
        migrations.AddField(
            model_name='shipdetail',
            name='is_elec',
            field=models.BooleanField(default=False, help_text='是否带电', null=True, verbose_name='是否带电'),
        ),
        migrations.AddField(
            model_name='shipdetail',
            name='is_magnet',
            field=models.BooleanField(default=False, help_text='是否带磁', null=True, verbose_name='是否带磁'),
        ),
        migrations.AddField(
            model_name='shipdetail',
            name='is_water',
            field=models.BooleanField(default=False, help_text='是否带液体', null=True, verbose_name='是否带液体'),
        ),
    ]
