# Generated by Django 3.2.4 on 2023-09-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0092_carriertrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriertrack',
            name='ship',
        ),
    ]
