# Generated by Django 3.2.4 on 2023-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0093_remove_carriertrack_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='platform',
            field=models.CharField(blank=True, help_text='平台', max_length=20, null=True, verbose_name='平台'),
        ),
    ]
