# Generated by Django 3.2.4 on 2023-10-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0100_refillsettings_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlorder',
            name='VAT',
            field=models.FloatField(default=0, help_text='税价', null=True, verbose_name='税价'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='buyer_id',
            field=models.CharField(blank=True, help_text='买家id', max_length=100, null=True, verbose_name='买家id'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, help_text='送达时间', null=True, verbose_name='送达时间'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='invoice_price',
            field=models.FloatField(default=0, help_text='成交价', null=True, verbose_name='成交价'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='platform',
            field=models.CharField(blank=True, help_text='平台', max_length=20, null=True, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='promo_coupon',
            field=models.FloatField(default=0, help_text='优惠金额', null=True, verbose_name='优惠金额'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='shipped_date',
            field=models.DateTimeField(blank=True, help_text='发货时间', null=True, verbose_name='发货时间'),
        ),
    ]
