# Generated by Django 3.2.4 on 2023-10-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0101_auto_20231008_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlorder',
            name='exc_currency',
            field=models.CharField(blank=True, help_text='币种', max_length=5, null=True, verbose_name='币种'),
        ),
    ]
