# Generated by Django 3.2.4 on 2023-10-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0104_auto_20231009_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0, help_text='当前库存', verbose_name='当前库存')),
                ('qty', models.IntegerField(default=0, help_text='变动数量', verbose_name='变动数量')),
                ('in_out', models.CharField(help_text='库存出入', max_length=5, verbose_name='库存出入')),
                ('action', models.CharField(help_text='变动来源', max_length=10, verbose_name='变动来源')),
                ('desc', models.CharField(help_text='变动来源', max_length=100, verbose_name='变动来源')),
                ('user_id', models.IntegerField(blank=True, default=0, help_text='操作人id', null=True, verbose_name='操作人id')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('shop_stock', models.ForeignKey(help_text='所属库存', on_delete=django.db.models.deletion.CASCADE, related_name='shop_stock_log', to='mercado.shopstock', verbose_name='所属库存')),
            ],
            options={
                'verbose_name': '库存日志',
                'verbose_name_plural': '库存日志',
                'ordering': ['-create_time'],
            },
        ),
    ]
