# Generated by Django 3.2.4 on 2023-10-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0105_stocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='desc',
            field=models.CharField(help_text='描述', max_length=100, verbose_name='描述'),
        ),
    ]
