# Generated by Django 3.2.4 on 2023-10-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0106_alter_stocklog_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_status', models.CharField(help_text='上传状态', max_length=10, verbose_name='上传状态')),
                ('upload_type', models.CharField(help_text='上传类型', max_length=10, verbose_name='上传类型')),
                ('desc', models.CharField(help_text='描述', max_length=100, verbose_name='描述')),
                ('user_id', models.IntegerField(blank=True, default=0, help_text='操作人id', null=True, verbose_name='操作人id')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('shop', models.ForeignKey(help_text='店铺', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_file_upload', to='mercado.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '文件上传通知',
                'verbose_name_plural': '文件上传通知',
                'ordering': ['-create_time'],
            },
        ),
    ]
