# Generated by Django 3.2.4 on 2023-10-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0107_fileuploadnotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadnotify',
            name='desc',
            field=models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述'),
        ),
    ]
