# Generated by Django 3.2.4 on 2023-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0108_alter_fileuploadnotify_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='carrier_GoodsNum',
            field=models.IntegerField(default=0, help_text='收货箱数', verbose_name='收货箱数'),
        ),
        migrations.AddField(
            model_name='ship',
            name='carrier_ckcbm',
            field=models.FloatField(blank=True, help_text='收货体积', null=True, verbose_name='收货体积'),
        ),
        migrations.AddField(
            model_name='ship',
            name='carrier_ckvolume',
            field=models.FloatField(blank=True, help_text='计费重量', null=True, verbose_name='计费重量'),
        ),
        migrations.AddField(
            model_name='ship',
            name='carrier_ckweight',
            field=models.FloatField(blank=True, help_text='收货重量', null=True, verbose_name='收货重量'),
        ),
        migrations.AddField(
            model_name='ship',
            name='carrier_order_status',
            field=models.CharField(blank=True, help_text='物流交运订单状态', max_length=10, null=True, verbose_name='物流交运订单状态'),
        ),
        migrations.AddField(
            model_name='ship',
            name='carrier_order_time',
            field=models.DateTimeField(blank=True, help_text='物流交运时间', null=True, verbose_name='物流交运时间'),
        ),
        migrations.AddField(
            model_name='ship',
            name='carrier_rec_check',
            field=models.CharField(blank=True, help_text='物流收货核查', max_length=10, null=True, verbose_name='物流收货核查'),
        ),
    ]
