# Generated by Django 3.2.4 on 2023-10-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0109_auto_20231021_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbmwarehouse',
            name='zip',
            field=models.CharField(blank=True, help_text='邮编', max_length=10, null=True, verbose_name='邮编'),
        ),
    ]
