# Generated by Django 3.2.4 on 2024-05-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0110_fbmwarehouse_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='项目名称', max_length=10, verbose_name='项目名称')),
                ('update_time', models.DateTimeField(blank=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('text1', models.CharField(blank=True, help_text='文本字段1', max_length=50, null=True, verbose_name='文本字段1')),
                ('text2', models.CharField(blank=True, help_text='文本字段2', max_length=50, null=True, verbose_name='文本字段2')),
                ('text3', models.CharField(blank=True, help_text='文本字段3', max_length=50, null=True, verbose_name='文本字段3')),
                ('value1', models.FloatField(blank=True, help_text='浮点字段1', null=True, verbose_name='浮点字段1')),
                ('value2', models.FloatField(blank=True, help_text='浮点字段2', null=True, verbose_name='浮点字段2')),
                ('value3', models.FloatField(blank=True, help_text='浮点字段3', null=True, verbose_name='浮点字段3')),
                ('num1', models.IntegerField(blank=True, default=0, help_text='整数字段1', null=True, verbose_name='整数字段1')),
                ('num2', models.IntegerField(blank=True, default=0, help_text='整数字段2', null=True, verbose_name='整数字段2')),
                ('num3', models.IntegerField(blank=True, default=0, help_text='整数字段3', null=True, verbose_name='整数字段3')),
                ('sw1', models.BooleanField(default=False, help_text='开关字段1', verbose_name='开关字段1')),
                ('sw2', models.BooleanField(default=False, help_text='开关字段2', verbose_name='开关字段2')),
                ('sw3', models.BooleanField(default=False, help_text='开关字段3', verbose_name='开关字段3')),
                ('d1', models.DateTimeField(blank=True, help_text='日期字段1', null=True, verbose_name='日期字段1')),
                ('d2', models.DateTimeField(blank=True, help_text='日期字段2', null=True, verbose_name='日期字段2')),
                ('d3', models.DateTimeField(blank=True, help_text='日期字段3', null=True, verbose_name='日期字段3')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '通用数据设置',
                'verbose_name_plural': '通用数据设置',
                'ordering': ['update_time'],
            },
        ),
        migrations.AddField(
            model_name='mlorder',
            name='dispatch_number',
            field=models.CharField(blank=True, help_text='发出编号', max_length=30, null=True, verbose_name='发出编号'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='fbo_fee',
            field=models.FloatField(blank=True, default=0, help_text='FBO费用', null=True, verbose_name='FBO费用'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='fee_rate',
            field=models.FloatField(blank=True, default=0, help_text='佣金率', null=True, verbose_name='佣金率'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='finance_check1',
            field=models.BooleanField(default=False, help_text='是否结算1', verbose_name='是否结算1'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='finance_check2',
            field=models.BooleanField(default=False, help_text='是否结算2', verbose_name='是否结算2'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='last_mile_fee',
            field=models.FloatField(blank=True, default=0, help_text='最后一公里费用', null=True, verbose_name='最后一公里费用'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='payment_fee',
            field=models.FloatField(blank=True, default=0, help_text='收单费用', null=True, verbose_name='收单费用'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='sp_fee',
            field=models.FloatField(blank=True, default=0, help_text='服务商费用', null=True, verbose_name='服务商费用'),
        ),
        migrations.AddField(
            model_name='mlorder',
            name='sp_fee_rate',
            field=models.FloatField(blank=True, default=0, help_text='服务商费率', null=True, verbose_name='服务商费率'),
        ),
    ]
