# Generated by Django 3.2.4 on 2024-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0111_auto_20240514_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='note',
            field=models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注'),
        ),
    ]
