# Generated by Django 3.2.4 on 2024-08-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0113_platformcategoryrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='国家', max_length=10, verbose_name='国家')),
                ('carrier_name', models.CharField(blank=True, help_text='物流名称', max_length=50, null=True, verbose_name='物流名称')),
                ('carrier_code', models.CharField(blank=True, help_text='物流代码', max_length=30, null=True, verbose_name='物流代码')),
                ('area', models.CharField(blank=True, help_text='分区', max_length=30, null=True, verbose_name='分区')),
                ('basic_price', models.FloatField(blank=True, help_text='基础价格', null=True, verbose_name='基础价格')),
                ('calc_price', models.FloatField(blank=True, help_text='计算价格', null=True, verbose_name='计算价格')),
                ('volume_ratio', models.IntegerField(blank=True, help_text='体积计算率', null=True, verbose_name='体积计算率')),
                ('min_weight', models.IntegerField(blank=True, help_text='区间最小重量g', null=True, verbose_name='区间最小重量g')),
                ('max_weight', models.IntegerField(blank=True, help_text='区间最大重量g', null=True, verbose_name='区间最大重量g')),
                ('is_elec', models.BooleanField(default=False, help_text='是否带电', verbose_name='是否带电')),
            ],
            options={
                'verbose_name': '虚拟仓物流价格',
                'verbose_name_plural': '虚拟仓物流价格',
            },
        ),
    ]
