# Generated by Django 3.2.4 on 2024-09-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0115_postcodedata_shippingareacode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCodeData',
        ),
    ]
