# Generated by Django 3.2.4 on 2026-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0116_delete_postcodedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlproduct',
            name='group_id',
            field=models.CharField(blank=True, help_text='组合id', max_length=40, null=True, verbose_name='组合id'),
        ),
        migrations.AddField(
            model_name='shopstock',
            name='group_id',
            field=models.CharField(blank=True, help_text='组合id', max_length=40, null=True, verbose_name='组合id'),
        ),
    ]
