# Generated by Django 3.2.4 on 2026-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0117_auto_20260425_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlorder',
            name='group_id',
            field=models.CharField(blank=True, help_text='合并ID', max_length=40, null=True, verbose_name='合并ID'),
        ),
    ]
