"""
Django settings for casedance project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os, datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 配置文件（所有环境差异统一管理）
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-only-change-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# 是否关闭网站
SITE_CLOSE = os.environ.get('SITE_CLOSE', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

BASE_URL = os.environ.get('BASE_URL', 'http://127.0.0.1:8000')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'product',  # 产品管理
    'setting',  # 系统设置
    'store',  # 仓库/商店模块
    'purchase',  # 采购模块
    'sale',  # 销售模块
    'report',  # 报告模块
    'bonus',  # 业绩提成app
    'mercado',  # 美客多app
    'devproduct',  # 产品开发app
    'productbase',  # 上架产品库app
    'feishu',  # 飞书集成（免登 + 通知）
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.VisitLimitMiddleWare',
]

ROOT_URLCONF = 'casedance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'casedance.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'casedance'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': int(os.environ.get('DB_PORT', '3306')),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES':
    ('rest_framework.permissions.IsAuthenticated', ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # 指定用于支持coreapi的Schema
    'DEFAULT_SCHEMA_CLASS':
    'rest_framework.schemas.coreapi.AutoSchema',
    # 时间格式：使用中国时间显示
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATETIME_INPUT_FORMATS': ['%Y-%m-%d %H:%M:%S'],
}

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

JWT_AUTH = {
    # 配置用户认证token有效期
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=30),
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'login_check.jwt_response_payload_handler',
    # 定义与令牌一起发送的Authorization标头值前缀
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
}

# celery相关配置
# 配置celery时区，默认时UTC。
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False

# 使用文件持久化调度器（非 django_celery_beat，兼容 USE_TZ=False）
CELERY_BEAT_SCHEDULER = 'celery.beat.PersistentScheduler'
CELERY_BEAT_SCHEDULE_FILENAME = 'celerybeat-schedule'

# 任务队列的链接地址 celery配置redis作为broker。redis有16个数据库，编号0~15，这里使用第1个。
CELERY_BROKER_URL = f'redis://{os.environ.get("REDIS_HOST", "127.0.0.1")}:{os.environ.get("REDIS_PORT", "6379")}/1'

# 设置存储结果的后台  结果队列的链接地址
CELERY_RESULT_BACKEND = f'redis://{os.environ.get("REDIS_HOST", "127.0.0.1")}:{os.environ.get("REDIS_PORT", "6379")}/0'

# 可接受的内容格式
CELERY_ACCEPT_CONTENT = ["json"]
# 任务序列化数据格式
CELERY_TASK_SERIALIZER = "json"
# 结果序列化数据格式
CELERY_RESULT_SERIALIZER = "json"
# 可选参数：给某个任务限流
# CELERY_TASK_ANNOTATIONS = {'tasks.my_task': {'rate_limit': '10/s'}}

# 可选参数：给任务设置超时时间。超时立即中止worker
# CELERY_TASK_TIME_LIMIT = 10 * 60

# 可选参数：给任务设置软超时时间，超时抛出Exception
# CELERY_TASK_SOFT_TIME_LIMIT = 10 * 60

# 数据库连接池：60 秒内复用同一连接，避免每次请求重建
CONN_MAX_AGE = 60

# ======================
# 外部服务 Token（从环境变量读取，不进 Git）
# ======================
SUPERBED_TOKEN = os.environ.get('SUPERBED_TOKEN', '')
CDN_RATE_LIMIT_PER_HOUR = int(os.environ.get('CDN_RATE_LIMIT_PER_HOUR', '1000'))
EBAY_CLIENT_ID = os.environ.get('EBAY_CLIENT_ID', '')
EBAY_CLIENT_SECRET = os.environ.get('EBAY_CLIENT_SECRET', '')

# Redis 配置（供飞书等模块使用）
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
REDIS_PORT = int(os.environ.get('REDIS_PORT', '6379'))
REDIS_DB = int(os.environ.get('REDIS_CACHE_DB', '1'))

# 飞书应用凭证
FEISHU_APP_ID = os.environ.get('FEISHU_APP_ID', '')
FEISHU_APP_SECRET = os.environ.get('FEISHU_APP_SECRET', '')

# ======================
# 盛德物流认证（优先读 env，否则从 sd_config.json 读取，兼容运行时写入）
# ======================
SD_COOKIES = os.environ.get('SD_COOKIES', '')
if not SD_COOKIES:
    import json as _json
    _sd_config_path = BASE_DIR / 'sd_config.json'
    if _sd_config_path.exists():
        try:
            with open(_sd_config_path, 'r', encoding='utf-8') as _f:
                SD_COOKIES = _json.load(_f).get('sd_cookies', '')
        except Exception:
            pass

# ======================
# Dify AI 配置（仅从环境变量读取）
# ======================
DIFY_INVOICE_APIKEY = os.environ.get('DIFY_INVOICE_APIKEY', '')
DIFY_EBAY_APIKEY = os.environ.get('DIFY_EBAY_APIKEY', '')
DIFY_HOST = os.environ.get('DIFY_HOST', '')
