# Generated by Django 3.2.4 on 2022-03-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRODUCT', '产品标签'), ('ORDER', '订单标签'), ('CUSTOMER', '客户标签')], default='PRODUCT', help_text='标签类型', max_length=10, verbose_name='标签类型')),
                ('color', models.CharField(help_text='标签颜色', max_length=10, verbose_name='标签颜色')),
                ('tag_name', models.CharField(help_text='标签名称', max_length=30, unique=True, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签库',
                'verbose_name_plural': '标签库',
            },
        ),
    ]
