# Generated by Django 3.2.4 on 2022-03-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_tag_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': '标签库', 'verbose_name_plural': '标签库'},
        ),
    ]
