# Generated by Django 3.2.4 on 2022-03-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(choices=[('PRODUCT', '产品操作'), ('ORDER', '销售单操作'), ('CUSTOMER', '客户管理操作'), ('PURCHASE', '采购单操作'), ('STORE', '店铺资料操作')], default='PRODUCT', help_text='日志类型', max_length=10, verbose_name='日志类型')),
                ('op_log', models.CharField(help_text='操作描述', max_length=300, verbose_name='操作描述')),
                ('target_id', models.IntegerField(blank=True, help_text='目标id', null=True, verbose_name='目标id')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='操作时间', verbose_name='操作时间')),
                ('user', models.ForeignKey(help_text='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_op_log', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-create_time'],
            },
        ),
    ]
