# Generated by Django 3.2.4 on 2022-04-08 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0005_alter_operatelog_op_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, help_text='路由地址', max_length=100, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, help_text='组件', max_length=30, null=True, verbose_name='组件')),
                ('name', models.CharField(blank=True, help_text='菜单名', max_length=30, null=True, verbose_name='菜单名')),
                ('icon', models.CharField(blank=True, help_text='icon图标', max_length=30, null=True, verbose_name='icon图标')),
                ('order_num', models.IntegerField(default=1, help_text='排序号', verbose_name='排序号')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, help_text='父id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setting.menu', verbose_name='父id')),
            ],
            options={
                'verbose_name': '前端导航菜单',
                'verbose_name_plural': '前端导航菜单',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('menu', models.ForeignKey(blank=True, help_text='导航菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_user_menu', to='setting.menu', verbose_name='导航菜单')),
                ('user', models.ForeignKey(help_text='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_u_menu', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '用户菜单',
                'verbose_name_plural': '用户菜单',
                'ordering': ['menu'],
            },
        ),
    ]
