# Generated by Django 3.2.4 on 2022-04-08 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_menu_usermenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='setting.menu', verbose_name='父id'),
        ),
    ]
