# Generated by Django 3.2.4 on 2022-04-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_menu_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMenu',
        ),
    ]
