# Generated by Django 3.2.4 on 2022-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_alter_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(help_text='标签名称', max_length=30, verbose_name='标签名称'),
        ),
    ]
