# Generated by Django 3.2.4 on 2022-05-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_tasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_alert_qty', models.IntegerField(default=0, help_text='警戒库存', verbose_name='警戒库存')),
                ('sys_mini_pq', models.IntegerField(default=0, help_text='最小采购量', verbose_name='最小采购量')),
                ('sys_max_pq', models.IntegerField(default=0, help_text='采购上限', verbose_name='采购上限')),
                ('sys_stock_days', models.IntegerField(default=0, help_text='备货天数', verbose_name='备货天数')),
            ],
            options={
                'verbose_name': '补货推荐设置',
                'verbose_name_plural': '补货推荐设置',
                'ordering': ['sys_alert_qty'],
            },
        ),
    ]
