# Generated by Django 3.2.4 on 2023-02-26 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0014_alter_tasklog_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(blank=True, help_text='组件名称', max_length=30, null=True, verbose_name='组件名称')),
                ('module_name', models.CharField(blank=True, help_text='模块名称', max_length=50, null=True, verbose_name='模块名称')),
                ('order_num', models.IntegerField(default=1, help_text='排序号', verbose_name='排序号')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, help_text='父id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='setting.mluserpermission', verbose_name='父id')),
                ('user', models.ForeignKey(help_text='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mlPermission', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '美客多操作权限',
                'verbose_name_plural': '美客多操作权限',
                'ordering': ['order_num'],
            },
        ),
    ]
