# Generated by Django 3.2.4 on 2026-07-23 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(help_text='飞书用户唯一标识', max_length=64, unique=True, verbose_name='飞书 Open ID')),
                ('mobile', models.CharField(blank=True, default='', help_text='飞书返回的手机号', max_length=20, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='绑定时间', verbose_name='绑定时间')),
                ('user', models.OneToOneField(help_text='关联的系统用户', on_delete=django.db.models.deletion.CASCADE, related_name='feishu_binding', to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '飞书用户绑定',
                'verbose_name_plural': '飞书用户绑定',
                'ordering': ['-create_time'],
            },
        ),
    ]
