# Generated by Django 3.2.4 on 2022-03-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_alter_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='公司名称', max_length=80, unique=True, verbose_name='公司名称')),
                ('customer_code', models.CharField(help_text='客户编码', max_length=20, unique=True, verbose_name='客户编码')),
                ('pay_way', models.CharField(choices=[('PAY_NOW', '现结'), ('CONTRACT', '约定付款')], default='FACTORY', help_text='结算类型', max_length=10, verbose_name='结算类型')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=200, null=True, verbose_name='地址')),
                ('contact_name', models.CharField(blank=True, help_text='联系人', max_length=20, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=15, null=True, verbose_name='电话')),
                ('qq', models.CharField(blank=True, help_text='QQ', max_length=15, null=True, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, help_text='微信', max_length=15, null=True, verbose_name='微信')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=50, null=True, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.IntegerField(default=1, help_text='折扣类型', verbose_name='折扣类型')),
                ('discount_money', models.FloatField(default=0.0, help_text='优惠额度', verbose_name='优惠额度')),
                ('discount_percent', models.FloatField(default=0.0, help_text='优惠比例', verbose_name='优惠比例')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('customer', models.ForeignKey(help_text='客户', on_delete=django.db.models.deletion.CASCADE, related_name='customer_discount', to='sale.customer', verbose_name='客户')),
                ('p_series', models.ForeignKey(help_text='产品系列', on_delete=django.db.models.deletion.CASCADE, related_name='p_series_discount', to='product.productextrainfo', verbose_name='产品系列')),
            ],
            options={
                'verbose_name': '客户专属优惠',
                'verbose_name_plural': '客户专属优惠',
                'ordering': ['create_time'],
            },
        ),
    ]
