# Generated by Django 3.2.4 on 2022-03-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_alter_operatelog_op_log'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(help_text='客户', on_delete=django.db.models.deletion.CASCADE, related_name='customer_tag', to='sale.customer', verbose_name='客户')),
                ('tag', models.ForeignKey(help_text='标签', on_delete=django.db.models.deletion.CASCADE, related_name='tag_customer_tag', to='setting.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '客户标签',
                'verbose_name_plural': '客户标签',
                'ordering': ['id'],
            },
        ),
    ]
