# Generated by Django 3.2.4 on 2022-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_customertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.IntegerField(default=1, help_text='客户评级', verbose_name='客户评级'),
        ),
    ]
