# Generated by Django 3.2.4 on 2022-04-01 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_auto_20220329_2246'),
        ('product', '0010_product_label_name'),
        ('sale', '0003_customer_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='销售单号', max_length=20, verbose_name='销售单号')),
                ('order_type', models.CharField(choices=[('PICKUP', '门店自提'), ('EXPRESS', '快递'), ('SELLER_SEND', '卖家送货')], default='PICKUP', help_text='订单类型', max_length=20, verbose_name='订单类型')),
                ('order_status', models.CharField(choices=[('CANCEL', '作废'), ('PRE_SUMMIT', '待处理'), ('PREPARING', '备货中'), ('READY', '已备货'), ('SENDING', '送货中'), ('PART_SENT', '部分发货'), ('FINISHED', '已完成'), ('EXCEPTION', '异常')], default='PRE_SUMMIT', help_text='订单状态', max_length=20, verbose_name='订单状态')),
                ('pay_way', models.CharField(choices=[('PAY_NOW', '现结'), ('CONTRACT', '约定付款')], default='PAY_NOW', help_text='结算类型', max_length=20, verbose_name='结算类型')),
                ('paid_status', models.CharField(choices=[('UNPAID', '未结算'), ('PART_PAID', '部分结算'), ('FULL_PAID', '全部结算')], default='UNPAID', help_text='结算状态', max_length=20, verbose_name='结算状态')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=200, null=True, verbose_name='地址')),
                ('contact_name', models.CharField(blank=True, help_text='联系人', max_length=20, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=15, null=True, verbose_name='电话')),
                ('logistic', models.CharField(blank=True, help_text='发货物流公司', max_length=20, null=True, verbose_name='发货物流公司')),
                ('tracking_number', models.CharField(blank=True, help_text='快递单号', max_length=30, null=True, verbose_name='快递单号')),
                ('postage', models.FloatField(default=0.0, help_text='采购运费', verbose_name='采购运费')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('customer', models.ForeignKey(help_text='客户', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_order', to='sale.customer', verbose_name='客户')),
                ('store', models.ForeignKey(help_text='收货仓库/店铺', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_order', to='store.store', verbose_name='收货仓库/店铺')),
                ('user', models.ForeignKey(help_text='操作人', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, help_text='销售数量', verbose_name='销售数量')),
                ('unit_price', models.FloatField(default=0.0, help_text='销售单价', verbose_name='销售单价')),
                ('sent_qty', models.IntegerField(default=0, help_text='发货数量', verbose_name='发货数量')),
                ('paid_qty', models.IntegerField(default=0, help_text='已结算数量', verbose_name='已结算数量')),
                ('is_paid', models.BooleanField(default=False, help_text='是否已结算', verbose_name='是否已结算')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('order', models.ForeignKey(help_text='所属销售单', on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='sale.order', verbose_name='所属销售单')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_order_detail', to='product.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '销售单明细',
                'verbose_name_plural': '销售单明细',
                'ordering': ['create_time'],
            },
        ),
    ]
