# Generated by Django 3.2.4 on 2022-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='sold_price',
            field=models.FloatField(default=0.0, help_text='成交价', verbose_name='成交价'),
        ),
    ]
