# Generated by Django 3.2.4 on 2022-04-01 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_alter_operatelog_op_log'),
        ('sale', '0005_orderdetail_sold_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(help_text='销售单', on_delete=django.db.models.deletion.CASCADE, related_name='order_tag', to='sale.order', verbose_name='销售单')),
                ('tag', models.ForeignKey(help_text='标签', on_delete=django.db.models.deletion.CASCADE, related_name='tag_order_tag', to='setting.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '销售单标签',
                'verbose_name_plural': '销售单标签',
                'ordering': ['id'],
            },
        ),
    ]
