# Generated by Django 3.2.4 on 2022-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_ordertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(help_text='销售单号', max_length=30, verbose_name='销售单号'),
        ),
    ]
