# Generated by Django 3.2.4 on 2022-04-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20220401_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CANCEL', '作废'), ('PREPARING', '备货中'), ('READY', '已备货'), ('PART_SENT', '部分发货'), ('FINISHED', '已完成'), ('EXCEPTION', '异常')], default='PREPARING', help_text='订单状态', max_length=20, verbose_name='订单状态'),
        ),
    ]
