# Generated by Django 3.2.4 on 2024-08-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevChannelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, help_text='平台', max_length=20, null=True, verbose_name='平台')),
                ('site', models.CharField(blank=True, help_text='站点', max_length=20, null=True, verbose_name='站点')),
                ('default_active', models.BooleanField(default=False, help_text='是否默认激活', null=True, verbose_name='是否默认激活')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '开发平台渠道数据',
                'verbose_name_plural': '开发平台渠道数据',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='DevProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='产品SKU', max_length=30, null=True, verbose_name='产品SKU')),
                ('cn_name', models.CharField(blank=True, help_text='产品中文名称', max_length=100, null=True, verbose_name='产品中文名称')),
                ('en_name', models.CharField(blank=True, help_text='产品英文名称', max_length=100, null=True, verbose_name='产品英文名称')),
                ('image', models.ImageField(blank=True, help_text='产品图片', max_length=200, null=True, upload_to='dev_product', verbose_name='产品图片')),
                ('is_elec', models.BooleanField(default=False, help_text='是否带电', null=True, verbose_name='是否带电')),
                ('is_magnet', models.BooleanField(default=False, help_text='是否带磁', null=True, verbose_name='是否带磁')),
                ('is_water', models.BooleanField(default=False, help_text='是否带液体', null=True, verbose_name='是否带液体')),
                ('is_dust', models.BooleanField(default=False, help_text='是否粉末', null=True, verbose_name='是否粉末')),
                ('is_confirm_data', models.BooleanField(default=False, help_text='是否确认重量尺寸', null=True, verbose_name='是否确认重量尺寸')),
                ('is_stock', models.BooleanField(default=False, help_text='是否有库存', null=True, verbose_name='是否有库存')),
                ('keywords', models.CharField(blank=True, help_text='搜索关键词', max_length=100, null=True, verbose_name='搜索关键词')),
                ('category', models.CharField(blank=True, help_text='产品分类', max_length=100, null=True, verbose_name='产品分类')),
                ('package_included', models.CharField(blank=True, help_text='产品清单', max_length=500, null=True, verbose_name='产品清单')),
                ('unit_cost', models.FloatField(blank=True, help_text='成本价', null=True, verbose_name='成本价')),
                ('p_length', models.FloatField(blank=True, help_text='长cm', null=True, verbose_name='长cm')),
                ('p_width', models.FloatField(blank=True, help_text='宽cm', null=True, verbose_name='宽cm')),
                ('p_height', models.FloatField(blank=True, help_text='高cm', null=True, verbose_name='高cm')),
                ('p_weight', models.FloatField(blank=True, help_text='重量g', null=True, verbose_name='重量g')),
                ('buy_url1', models.CharField(blank=True, help_text='产品采购链接1', max_length=500, null=True, verbose_name='产品采购链接1')),
                ('buy_url2', models.CharField(blank=True, help_text='产品采购链接2', max_length=500, null=True, verbose_name='产品采购链接2')),
                ('buy_url3', models.CharField(blank=True, help_text='产品采购链接3', max_length=500, null=True, verbose_name='产品采购链接3')),
                ('buy_url4', models.CharField(blank=True, help_text='产品采购链接4', max_length=500, null=True, verbose_name='产品采购链接4')),
                ('buy_url5', models.CharField(blank=True, help_text='产品采购链接5', max_length=500, null=True, verbose_name='产品采购链接5')),
                ('refer_url1', models.CharField(blank=True, help_text='参考链接1', max_length=500, null=True, verbose_name='参考链接1')),
                ('refer_url2', models.CharField(blank=True, help_text='参考链接2', max_length=500, null=True, verbose_name='参考链接2')),
                ('desc', models.TextField(blank=True, default='', help_text='产品描述', null=True, verbose_name='产品描述')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('online_time', models.DateTimeField(blank=True, help_text='发布时间', null=True, verbose_name='发布时间')),
                ('offline_time', models.DateTimeField(auto_now_add=True, help_text='下架时间', verbose_name='下架时间')),
                ('user_id', models.IntegerField(blank=True, default=0, help_text='创建人id', null=True, verbose_name='创建人id')),
                ('qty', models.IntegerField(blank=True, help_text='库存数量', null=True, verbose_name='库存数量')),
                ('percent', models.IntegerField(blank=True, help_text='上架完成百分比', null=True, verbose_name='上架完成百分比')),
                ('rate', models.IntegerField(blank=True, help_text='产品评分', null=True, verbose_name='产品评分')),
                ('p_status', models.CharField(blank=True, help_text='状态', max_length=15, null=True, verbose_name='状态')),
                ('buy_status', models.CharField(blank=True, help_text='备货状态', max_length=15, null=True, verbose_name='备货状态')),
                ('tag_name', models.CharField(blank=True, help_text='标签名称', max_length=100, null=True, verbose_name='标签名称')),
                ('tag_color', models.CharField(blank=True, help_text='标签颜色', max_length=20, null=True, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '产品开发列表',
                'verbose_name_plural': '产品开发列表',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DevPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, help_text='平台', max_length=20, null=True, verbose_name='平台')),
                ('site', models.CharField(blank=True, help_text='站点', max_length=20, null=True, verbose_name='站点')),
                ('currency', models.CharField(blank=True, help_text='币种', max_length=10, null=True, verbose_name='币种')),
                ('price', models.FloatField(blank=True, default=0, help_text='定价', null=True, verbose_name='定价')),
                ('profit', models.FloatField(blank=True, default=0, help_text='毛利润', null=True, verbose_name='毛利润')),
                ('gross_margin', models.FloatField(blank=True, default=0, help_text='毛利率', null=True, verbose_name='毛利率')),
                ('ex_rate', models.FloatField(blank=True, default=0, help_text='汇率', null=True, verbose_name='汇率')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('ship', models.ForeignKey(help_text='所属开发产品', on_delete=django.db.models.deletion.CASCADE, related_name='dev_price', to='devproduct.devproduct', verbose_name='所属开发产品')),
            ],
            options={
                'verbose_name': '产品开发定价',
                'verbose_name_plural': '产品开发定价',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='DevListingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, help_text='平台', max_length=20, null=True, verbose_name='平台')),
                ('site', models.CharField(blank=True, help_text='站点', max_length=20, null=True, verbose_name='站点')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('ship', models.ForeignKey(help_text='所属开发产品', on_delete=django.db.models.deletion.CASCADE, related_name='dev_listing_channel', to='devproduct.devproduct', verbose_name='所属开发产品')),
            ],
            options={
                'verbose_name': '开发产品发布渠道',
                'verbose_name_plural': '开发产品发布渠道',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DevListingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, help_text='平台', max_length=20, null=True, verbose_name='平台')),
                ('site', models.CharField(blank=True, help_text='站点', max_length=20, null=True, verbose_name='站点')),
                ('account_name', models.CharField(blank=True, help_text='账号名称', max_length=50, null=True, verbose_name='账号名称')),
                ('user_id', models.IntegerField(blank=True, default=0, help_text='负责人id', null=True, verbose_name='负责人id')),
                ('user_name', models.CharField(blank=True, help_text='负责姓名', max_length=20, null=True, verbose_name='负责姓名')),
                ('item_id', models.CharField(blank=True, help_text='产品在线id', max_length=30, null=True, verbose_name='产品在线id')),
                ('is_online', models.BooleanField(default=False, help_text='是否已上架', null=True, verbose_name='是否已上架')),
                ('online_time', models.DateTimeField(blank=True, help_text='上架时间', null=True, verbose_name='上架时间')),
                ('offline_time', models.DateTimeField(blank=True, help_text='下架时间', null=True, verbose_name='下架时间')),
                ('note', models.CharField(blank=True, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('ship', models.ForeignKey(help_text='所属开发产品', on_delete=django.db.models.deletion.CASCADE, related_name='dev_listing_account', to='devproduct.devproduct', verbose_name='所属开发产品')),
            ],
            options={
                'verbose_name': '开发产品上架账号',
                'verbose_name_plural': '开发产品上架账号',
                'ordering': ['id'],
            },
        ),
    ]
