# Generated by Django 3.2.4 on 2024-08-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devlistingaccount',
            old_name='ship',
            new_name='dev_p',
        ),
        migrations.RenameField(
            model_name='devlistingchannel',
            old_name='ship',
            new_name='dev_p',
        ),
        migrations.RenameField(
            model_name='devprice',
            old_name='ship',
            new_name='dev_p',
        ),
    ]
