# Generated by Django 3.2.4 on 2024-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0002_auto_20240823_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devproduct',
            name='offline_time',
            field=models.DateTimeField(blank=True, help_text='下架时间', null=True, verbose_name='下架时间'),
        ),
    ]
