# Generated by Django 3.2.4 on 2024-08-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0003_alter_devproduct_offline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devproduct',
            name='online_time',
            field=models.DateTimeField(help_text='发布时间', null=True, verbose_name='发布时间'),
        ),
    ]
