# Generated by Django 3.2.4 on 2024-08-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0005_alter_devproduct_online_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devproduct',
            name='online_time',
        ),
    ]
