# Generated by Django 3.2.4 on 2024-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0006_remove_devproduct_online_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='devproduct',
            name='online_time',
            field=models.DateTimeField(blank=True, help_text='发布时间', null=True, verbose_name='发布时间'),
        ),
    ]
