# Generated by Django 3.2.4 on 2024-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0010_auto_20240902_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='devlistingaccount',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
    ]
