# Generated by Django 3.2.4 on 2024-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0011_devlistingaccount_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='devproduct',
            name='cp_id',
            field=models.IntegerField(blank=True, help_text='关联识别码', null=True, verbose_name='关联识别码'),
        ),
    ]
