# Generated by Django 3.2.4 on 2024-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0012_devproduct_cp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devproduct',
            name='rate',
            field=models.IntegerField(blank=True, default=0, help_text='产品评分', null=True, verbose_name='产品评分'),
        ),
    ]
