# Generated by Django 3.2.4 on 2024-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0013_alter_devproduct_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devproduct',
            name='local_category',
            field=models.IntegerField(blank=True, default=0, help_text='产品目录', null=True, verbose_name='产品目录'),
        ),
    ]
