# Generated by Django 3.2.4 on 2024-09-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0016_auto_20240912_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_p_id', models.IntegerField(blank=True, help_text='开发产品id', null=True, verbose_name='开发产品id')),
                ('platform', models.CharField(blank=True, help_text='平台', max_length=20, null=True, verbose_name='平台')),
                ('site', models.CharField(blank=True, help_text='站点', max_length=20, null=True, verbose_name='站点')),
                ('currency', models.CharField(blank=True, help_text='币种', max_length=10, null=True, verbose_name='币种')),
                ('sku', models.CharField(blank=True, help_text='产品SKU', max_length=30, null=True, verbose_name='产品SKU')),
                ('cn_name', models.CharField(blank=True, help_text='产品中文名称', max_length=100, null=True, verbose_name='产品中文名称')),
                ('image', models.ImageField(blank=True, help_text='产品图片', max_length=200, null=True, upload_to='', verbose_name='产品图片')),
                ('account_name', models.CharField(blank=True, help_text='账号名称', max_length=50, null=True, verbose_name='账号名称')),
                ('item_id', models.CharField(blank=True, help_text='产品在线id', max_length=30, null=True, verbose_name='产品在线id')),
                ('order_number', models.CharField(blank=True, help_text='订单编号', max_length=30, null=True, verbose_name='订单编号')),
                ('order_status', models.CharField(blank=True, help_text='订单状态', max_length=10, null=True, verbose_name='订单状态')),
                ('order_time', models.DateTimeField(blank=True, help_text='订单时间', null=True, verbose_name='订单时间')),
                ('qty', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('ex_rate', models.FloatField(blank=True, default=0, help_text='汇率', null=True, verbose_name='汇率')),
                ('item_price', models.FloatField(blank=True, default=0, help_text='销售单价', null=True, verbose_name='销售单价')),
                ('postage_price', models.FloatField(blank=True, default=0, help_text='收取运费', null=True, verbose_name='收取运费')),
                ('total_price', models.FloatField(blank=True, default=0, help_text='销售总价', null=True, verbose_name='销售总价')),
                ('fees', models.FloatField(blank=True, default=0, help_text='佣金', null=True, verbose_name='佣金')),
                ('postage', models.FloatField(blank=True, default=0, help_text='发货邮费', null=True, verbose_name='发货邮费')),
                ('receive_fund', models.FloatField(blank=True, default=0, help_text='收入资金', null=True, verbose_name='收入资金')),
                ('profit', models.FloatField(blank=True, default=0, help_text='利润rmb', null=True, verbose_name='利润rmb')),
                ('profit_rate', models.FloatField(blank=True, default=0, help_text='毛利率', null=True, verbose_name='毛利率')),
                ('is_ad', models.BooleanField(default=False, help_text='是否广告卖出', verbose_name='是否广告卖出')),
                ('ad_fee', models.FloatField(blank=True, default=0, help_text='广告费', null=True, verbose_name='广告费')),
                ('is_combined', models.BooleanField(default=False, help_text='是否合并订单', verbose_name='是否合并订单')),
                ('is_settled', models.BooleanField(default=False, help_text='是否已结算', verbose_name='是否已结算')),
            ],
            options={
                'verbose_name': '开发产品订单',
                'verbose_name_plural': '开发产品订单',
                'ordering': ['order_time'],
            },
        ),
        migrations.AddField(
            model_name='devlistingaccount',
            name='total_sold',
            field=models.IntegerField(default=0, help_text='累计销量', verbose_name='累计销量'),
        ),
        migrations.AddField(
            model_name='devproduct',
            name='avg_profit',
            field=models.FloatField(blank=True, help_text='平均毛利润', null=True, verbose_name='平均毛利润'),
        ),
        migrations.AddField(
            model_name='devproduct',
            name='avg_profit_rate',
            field=models.FloatField(blank=True, help_text='平均毛利率', null=True, verbose_name='平均毛利率'),
        ),
        migrations.AddField(
            model_name='devproduct',
            name='day15_sold',
            field=models.IntegerField(default=0, help_text='15天销量', verbose_name='15天销量'),
        ),
        migrations.AddField(
            model_name='devproduct',
            name='day30_sold',
            field=models.IntegerField(default=0, help_text='30天销量', verbose_name='30天销量'),
        ),
        migrations.AddField(
            model_name='devproduct',
            name='day7_sold',
            field=models.IntegerField(default=0, help_text='7天销量', verbose_name='7天销量'),
        ),
        migrations.AddField(
            model_name='devproduct',
            name='total_profit',
            field=models.FloatField(blank=True, help_text='累计利润', null=True, verbose_name='累计利润'),
        ),
        migrations.AddField(
            model_name='devproduct',
            name='total_sold',
            field=models.IntegerField(default=0, help_text='累计销量', verbose_name='累计销量'),
        ),
    ]
