# Generated by Django 3.2.4 on 2024-09-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0018_devorder_is_resent'),
    ]

    operations = [
        migrations.AddField(
            model_name='devlistingaccount',
            name='unit_cost',
            field=models.FloatField(blank=True, help_text='成本价', null=True, verbose_name='成本价'),
        ),
    ]
