# Generated by Django 3.2.4 on 2024-10-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0020_auto_20240914_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='devchanneldata',
            name='only_local',
            field=models.BooleanField(default=False, help_text='是否仅本土号', null=True, verbose_name='是否仅本土号'),
        ),
        migrations.AddField(
            model_name='devlistingchannel',
            name='only_local',
            field=models.BooleanField(default=False, help_text='是否仅本土号', null=True, verbose_name='是否仅本土号'),
        ),
    ]
