# Generated by Django 3.2.4 on 2024-10-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0021_auto_20241018_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devchanneldata',
            old_name='only_local',
            new_name='include_china',
        ),
        migrations.RenameField(
            model_name='devlistingchannel',
            old_name='only_local',
            new_name='include_china',
        ),
    ]
