# Generated by Django 3.2.4 on 2024-10-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0022_auto_20241018_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devchanneldata',
            name='include_china',
            field=models.BooleanField(default=False, help_text='包含跨境号', null=True, verbose_name='包含跨境号'),
        ),
        migrations.AlterField(
            model_name='devlistingchannel',
            name='include_china',
            field=models.BooleanField(default=False, help_text='包含跨境号', null=True, verbose_name='包含跨境号'),
        ),
    ]
