# Generated by Django 3.2.4 on 2024-10-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproduct', '0023_auto_20241018_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='devlistingaccount',
            name='ac_type',
            field=models.CharField(blank=True, default='CHINA', help_text='账号类型', max_length=10, null=True, verbose_name='账号类型'),
        ),
    ]
