# Generated by Django 3.2.4 on 2026-05-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_status', models.CharField(max_length=30, verbose_name='产品状态')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='产品类目')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('series', models.CharField(blank=True, max_length=100, verbose_name='产品系列')),
                ('tag', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '基础产品组',
                'verbose_name_plural': '基础产品组',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='变体标题')),
                ('desc', models.TextField(blank=True, verbose_name='变体描述')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU编码')),
                ('p_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('currency', models.CharField(max_length=20, verbose_name='币种')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本')),
                ('UPC', models.CharField(blank=True, max_length=50, verbose_name='UPC码')),
                ('var1', models.CharField(blank=True, max_length=100, verbose_name='变体属性值1')),
                ('var2', models.CharField(blank=True, max_length=100, verbose_name='变体属性值2')),
                ('var3', models.CharField(blank=True, max_length=100, verbose_name='变体属性值3')),
                ('var4', models.CharField(blank=True, max_length=100, verbose_name='变体属性值4')),
                ('custom_attributes', models.JSONField(blank=True, null=True, verbose_name='自定义属性')),
                ('purchase_url', models.CharField(blank=True, max_length=500, verbose_name='采购链接')),
            ],
            options={
                'verbose_name': '产品变体',
                'verbose_name_plural': '产品变体',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_account', models.CharField(max_length=100, verbose_name='店铺账号')),
                ('platform', models.CharField(max_length=50, verbose_name='所属平台')),
                ('title', models.CharField(max_length=200, verbose_name='产品组标题')),
                ('site', models.CharField(max_length=50, verbose_name='站点')),
                ('variant_name', models.CharField(blank=True, max_length=200, verbose_name='变体属性名称')),
                ('desc', models.TextField(blank=True, verbose_name='产品组描述')),
                ('custom_attributes', models.JSONField(blank=True, null=True, verbose_name='自定义属性')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='productbase.baseproductgroup', verbose_name='关联基础产品组')),
            ],
            options={
                'verbose_name': '店铺产品组',
                'verbose_name_plural': '店铺产品组',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500, verbose_name='图片地址')),
                ('sort', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_cover', models.BooleanField(default=False, verbose_name='是否封面图')),
                ('base_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productbase.baseproductgroup', verbose_name='关联基础产品组')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productbase.productgroup', verbose_name='关联店铺产品组')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productbase.product', verbose_name='关联产品变体')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['sort'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='productbase.productgroup', verbose_name='所属店铺产品组'),
        ),
    ]
