# Generated by Django 3.2.4 on 2026-05-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproductgroup',
            name='from_item_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='源id'),
        ),
        migrations.AddField(
            model_name='baseproductgroup',
            name='from_platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='源平台'),
        ),
        migrations.AddField(
            model_name='baseproductgroup',
            name='from_site_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='源站点'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='p_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='产品状态'),
        ),
    ]
