# Generated by Django 3.2.4 on 2026-05-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0002_auto_20260520_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, verbose_name='商品ID')),
                ('marketplace_id', models.CharField(max_length=30, verbose_name='站点ID')),
                ('platform', models.CharField(default='EBAY', max_length=30, verbose_name='平台')),
                ('status', models.CharField(choices=[('PENDING', '待抓取'), ('PROCESSING', '抓取中'), ('SUCCESS', '已抓取'), ('FAILED', '异常')], default='PENDING', max_length=20, verbose_name='任务状态')),
                ('log', models.TextField(blank=True, verbose_name='任务日志')),
                ('creator', models.CharField(default='system', max_length=50, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('base_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productbase.baseproductgroup', verbose_name='关联基础产品组')),
            ],
            options={
                'verbose_name': '抓取任务',
                'verbose_name_plural': '抓取任务',
                'ordering': ['-create_time'],
            },
        ),
    ]
