# Generated by Django 3.2.4 on 2026-05-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0003_fetchtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU编码')),
                ('p_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('UPC', models.CharField(blank=True, max_length=50, verbose_name='UPC码')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本')),
                ('purchase_url', models.CharField(blank=True, max_length=500, verbose_name='采购链接')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_skus', to='productbase.baseproductgroup', verbose_name='所属基础产品组')),
            ],
            options={
                'verbose_name': 'SKU核心数据',
                'verbose_name_plural': 'SKU核心数据',
            },
        ),
        migrations.CreateModel(
            name='ProductShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='变体标题')),
                ('desc', models.TextField(blank=True, verbose_name='变体描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('currency', models.CharField(max_length=20, verbose_name='币种')),
                ('var1', models.CharField(blank=True, max_length=100, verbose_name='变体属性值1')),
                ('var2', models.CharField(blank=True, max_length=100, verbose_name='变体属性值2')),
                ('var3', models.CharField(blank=True, max_length=100, verbose_name='变体属性值3')),
                ('var4', models.CharField(blank=True, max_length=100, verbose_name='变体属性值4')),
                ('custom_attributes', models.JSONField(blank=True, null=True, verbose_name='自定义属性')),
                ('core_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_records', to='productbase.productcore', verbose_name='关联核心SKU')),
            ],
            options={
                'verbose_name': '店铺SKU数据',
                'verbose_name_plural': '店铺SKU数据',
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='站点'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='productshop',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_skus', to='productbase.productgroup', verbose_name='所属店铺产品组'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_core',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productbase.productcore', verbose_name='关联核心SKU'),
        ),
        migrations.AlterUniqueTogether(
            name='productshop',
            unique_together={('group', 'core_sku')},
        ),
    ]
