# Generated by Django 3.2.4 on 2026-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0004_auto_20260526_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='是否主店铺'),
        ),
    ]
