# Generated by Django 3.2.4 on 2026-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0005_productgroup_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproductgroup',
            name='var_mappings',
            field=models.JSONField(blank=True, default=dict, verbose_name='变体值翻译映射'),
        ),
    ]
