# Generated by Django 3.2.4 on 2026-06-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0006_baseproductgroup_var_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('purchase_channel', models.CharField(blank=True, max_length=200, verbose_name='采购渠道')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='链接地址')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=50, verbose_name='QQ')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_list', to='productbase.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '产品系列',
                'verbose_name_plural': '产品系列',
                'ordering': ['-create_time'],
            },
        ),
    ]
