# Generated by Django 3.2.4 on 2026-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0007_productseries_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='名称'),
        ),
    ]
