# Generated by Django 3.2.4 on 2026-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0008_alter_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='操作用户')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('action', models.CharField(choices=[('CREATE', '新增'), ('UPDATE', '修改'), ('DELETE', '删除')], max_length=10, verbose_name='操作类型')),
                ('target_type', models.CharField(max_length=50, verbose_name='目标类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('detail', models.TextField(blank=True, verbose_name='操作描述')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='请求数据快照')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-create_time'],
            },
        ),
    ]
