# Generated by Django 3.2.4 on 2026-06-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0009_operationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '创建产品'), ('UPDATE', '修改产品'), ('ADD_SHOP', '新增店铺'), ('DELETE_SHOP', '删除店铺'), ('ADD_SKU', '新增SKU'), ('DELETE_SKU', '删除SKU'), ('STATUS_CHANGE', '状态变更'), ('IMAGE_MIGRATE', '图片迁移完成')], max_length=20, verbose_name='操作类型')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('operator', models.CharField(default='system', max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('base_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='productbase.baseproductgroup', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '产品操作日志',
                'verbose_name_plural': '产品操作日志',
                'ordering': ['-create_time'],
            },
        ),
        migrations.DeleteModel(
            name='OperationLog',
        ),
    ]
