# Generated by Django 3.2.4 on 2026-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0010_auto_20260610_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproductgroup',
            name='image_migrated',
            field=models.BooleanField(default=False, verbose_name='图片迁移完成'),
        ),
    ]
