# Generated by Django 3.2.4 on 2026-06-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0011_baseproductgroup_image_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproductgroup',
            name='variant_mapped',
            field=models.BooleanField(default=False, verbose_name='变体映射完成'),
        ),
    ]
