# Generated by Django 3.2.4 on 2026-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0012_baseproductgroup_variant_mapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcore',
            name='sku_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间'),
        ),
        migrations.AddField(
            model_name='productcore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
