# Generated by Django 3.2.4 on 2026-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0013_auto_20260611_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='shop_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
