# Generated by Django 3.2.4 on 2026-06-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0014_auto_20260612_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproductgroup',
            name='category_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='类目ID路径'),
        ),
    ]
