# Generated by Django 3.2.4 on 2026-06-15 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productbase', '0015_baseproductgroup_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('promoted_listing_enabled', models.BooleanField(default=False, verbose_name='是否应用Promoted Listing')),
                ('promoted_listing_ad_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Promoted Listing广告费率')),
                ('campaign', models.TextField(blank=True, verbose_name='Campaign')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_configs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '广告配置',
                'verbose_name_plural': '广告配置',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ListingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('default_stock', models.IntegerField(default=0, verbose_name='默认在线初始库存')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('listing_template', models.TextField(blank=True, verbose_name='通用刊登模板')),
                ('payment_method', models.TextField(blank=True, verbose_name='付款方式')),
                ('shipping_method', models.TextField(blank=True, verbose_name='货运方式')),
                ('excluded_regions', models.TextField(blank=True, verbose_name='不运送地区')),
                ('buyer_requirements', models.TextField(blank=True, verbose_name='买家要求')),
                ('return_policy', models.TextField(blank=True, verbose_name='退货政策')),
                ('item_location', models.CharField(blank=True, max_length=200, verbose_name='物品所在地')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_configs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '刊登配置',
                'verbose_name_plural': '刊登配置',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('shop_account', models.CharField(max_length=100, verbose_name='店铺账号')),
                ('site', models.CharField(blank=True, max_length=50, verbose_name='站点')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否主店铺')),
                ('auto_create_shop', models.BooleanField(default=True, verbose_name='创建产品时自动创建店铺')),
                ('advertising_enabled', models.BooleanField(default=False, verbose_name='是否启用广告')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('advertising_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_configs', to='productbase.advertisingconfig', verbose_name='广告配置')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shop_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('listing_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_configs', to='productbase.listingconfig', verbose_name='刊登配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_configs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '店铺配置',
                'verbose_name_plural': '店铺配置',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='FetchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('keep_attributes', models.JSONField(default=list, verbose_name='属性保留白名单')),
                ('fixed_attributes', models.JSONField(default=dict, verbose_name='固定附加属性')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_configs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '抓取配置',
                'verbose_name_plural': '抓取配置',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='productgroup',
            name='shop_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_product_groups', to='productbase.shopconfig', verbose_name='关联店铺配置'),
        ),
        migrations.AddConstraint(
            model_name='fetchconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_fetch_config_per_user'),
        ),
    ]
