# Generated by Django 3.2.4 on 2026-06-16 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productbase', '0016_auto_20260615_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='shop_config',
        ),
        migrations.AddField(
            model_name='listingconfig',
            name='campaign',
            field=models.TextField(blank=True, verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='listingconfig',
            name='promoted_listing_ad_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Promoted Listing广告费率'),
        ),
        migrations.AddField(
            model_name='listingconfig',
            name='promoted_listing_enabled',
            field=models.BooleanField(default=False, verbose_name='是否应用Promoted Listing'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='listing_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_product_groups', to='productbase.listingconfig', verbose_name='关联刊登配置'),
        ),
        migrations.AlterUniqueTogether(
            name='shopconfig',
            unique_together={('user', 'platform', 'shop_account', 'site')},
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='advertising_config',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='advertising_enabled',
        ),
        migrations.DeleteModel(
            name='AdvertisingConfig',
        ),
    ]
