# Generated by Django 3.2.4 on 2026-06-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0017_auto_20260616_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingconfig',
            name='discount',
            field=models.TextField(blank=True, verbose_name='折扣'),
        ),
        migrations.AddField(
            model_name='listingconfig',
            name='sale_plan',
            field=models.TextField(blank=True, verbose_name='销售计划'),
        ),
    ]
