# Generated by Django 3.2.4 on 2026-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0018_auto_20260617_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingconfig',
            name='match_shop_account',
            field=models.CharField(blank=True, max_length=200, verbose_name='匹配店铺账号'),
        ),
        migrations.AddField(
            model_name='listingconfig',
            name='match_site',
            field=models.CharField(blank=True, max_length=100, verbose_name='匹配站点'),
        ),
    ]
