# Generated by Django 3.2.4 on 2026-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0020_add_pricing_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproductgroup',
            name='primary_variant',
            field=models.CharField(blank=True, max_length=50, verbose_name='主属性（控制图片切换）'),
        ),
    ]
