# Generated by Django 3.2.4 on 2026-06-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0021_add_primary_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='base_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='productbase.baseproductgroup', verbose_name='关联产品'),
        ),
    ]
