# Generated by Django 3.2.4 on 2026-06-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productbase', '0022_productlog_set_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimize_type', models.CharField(max_length=20, verbose_name='优化类型')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示词 Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='生成 Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总 Token')),
                ('total_price', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='费用(RMB)')),
                ('currency', models.CharField(default='RMB', max_length=10, verbose_name='币种')),
                ('latency', models.FloatField(default=0, verbose_name='延迟(秒)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dify_usage_logs', to='productbase.productgroup', verbose_name='关联店铺')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dify_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='调用用户')),
            ],
            options={
                'verbose_name': 'Dify 调用记录',
                'verbose_name_plural': 'Dify 调用记录',
                'ordering': ['-create_time'],
            },
        ),
    ]
