# Generated by Django 3.2.4 on 2026-06-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0024_optimize_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantMappingAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(help_text='单个属性名，如 color。匹配不区分大小写', max_length=100, unique=True, verbose_name='变体属性名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '变体映射属性',
                'verbose_name_plural': '变体映射属性',
                'ordering': ['attribute_name'],
            },
        ),
        migrations.CreateModel(
            name='VariantMappingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_pattern', models.CharField(help_text='待匹配的前缀文本，如: For Samsung', max_length=200, verbose_name='匹配模式')),
                ('replace_value', models.CharField(help_text='匹配后替换为的值，如: 三星', max_length=200, verbose_name='替换值')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='productbase.variantmappingattribute', verbose_name='所属属性')),
            ],
            options={
                'verbose_name': '变体映射值',
                'verbose_name_plural': '变体映射值',
                'unique_together': {('attribute', 'match_pattern')},
            },
        ),
    ]
