# Generated by Django 3.2.4 on 2026-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0025_variantmappingattribute_variantmappingvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantmappingattribute',
            name='attribute_name',
            field=models.CharField(help_text='属性名，多个用逗号分隔为 OR 关系。如: color,colour', max_length=200, unique=True, verbose_name='变体属性名'),
        ),
    ]
