# Generated by Django 3.2.4 on 2026-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0027_alter_productlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, help_text='精确匹配 eBay categoryIdPath，如: 150|173444', max_length=200, verbose_name='类目ID')),
                ('category_name', models.CharField(blank=True, help_text='子串匹配 categoryPath（大小写不敏感），如: Cases', max_length=200, verbose_name='类目名称')),
                ('warehouse', models.CharField(help_text='匹配到的仓库，如: F仓、华强仓', max_length=100, verbose_name='仓库名称')),
                ('priority', models.IntegerField(default=0, help_text='数值越大越优先匹配', verbose_name='优先级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '仓库匹配配置',
                'verbose_name_plural': '仓库匹配配置',
                'ordering': ['-priority', '-create_time'],
            },
        ),
        migrations.AddField(
            model_name='productcore',
            name='warehouse',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='仓库'),
        ),
    ]
