# Generated by Django 3.2.4 on 2026-06-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0028_auto_20260630_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantmappingvalue',
            options={'ordering': ['-priority'], 'verbose_name': '变体映射值', 'verbose_name_plural': '变体映射值'},
        ),
        migrations.AddField(
            model_name='variantmappingvalue',
            name='priority',
            field=models.IntegerField(default=0, help_text='数值越大越优先匹配。同属性下长模式应设置更高优先级', verbose_name='优先级'),
        ),
    ]
