# Generated by Django 3.2.4 on 2026-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0029_auto_20260630_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='action',
            field=models.CharField(choices=[('CREATE', '创建产品'), ('UPDATE', '修改产品'), ('ADD_SHOP', '新增店铺'), ('DELETE_SHOP', '删除店铺'), ('ADD_SKU', '新增SKU'), ('DELETE_SKU', '删除SKU'), ('STATUS_CHANGE', '状态变更'), ('IMAGE_MIGRATE', '图片迁移完成'), ('OPTIMIZE_TITLE', '优化标题'), ('OPTIMIZE_DESC', '优化描述'), ('VARIANT', '变体映射'), ('PRICE_RULE', '定价规则'), ('WAREHOUSE', '仓库匹配')], max_length=20, verbose_name='操作类型'),
        ),
    ]
