# Generated by Django 3.2.4 on 2026-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0030_alter_productlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_total', models.IntegerField(default=0, verbose_name='CDN 总数')),
                ('db_total', models.IntegerField(default=0, verbose_name='DB 总数')),
                ('migrated', models.IntegerField(default=0, verbose_name='已迁移')),
                ('unmigrated', models.IntegerField(default=0, verbose_name='未迁移')),
                ('orphan', models.IntegerField(default=0, verbose_name='孤儿数')),
                ('computing', models.BooleanField(default=False, verbose_name='计算中')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图片统计缓存',
                'verbose_name_plural': '图片统计缓存',
            },
        ),
    ]
