# Generated by Django 3.2.4 on 2026-07-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0031_imagestatscache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproductgroup',
            name='category',
            field=models.CharField(blank=True, max_length=500, verbose_name='产品类目'),
        ),
    ]
