# Generated by Django 3.2.4 on 2026-07-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0032_alter_baseproductgroup_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcore',
            name='mb_product_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='MB产品状态'),
        ),
        migrations.AddField(
            model_name='warehouseconfig',
            name='mb_product_status',
            field=models.CharField(blank=True, help_text='匹到的仓库关联的MB状态，如: 正常销售、商品清仓', max_length=50, verbose_name='MB产品状态'),
        ),
        migrations.AlterField(
            model_name='warehouseconfig',
            name='category_id',
            field=models.CharField(blank=True, help_text='前缀匹配 eBay categoryIdPath，如: 15032 可匹配 15032|9394|20349', max_length=200, verbose_name='类目ID'),
        ),
    ]
