# Generated by Django 3.2.4 on 2026-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0033_auto_20260704_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='auto_optimize_desc',
            field=models.BooleanField(default=False, verbose_name='自动AI优化描述'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='auto_optimize_title',
            field=models.BooleanField(default=False, verbose_name='自动AI优化标题'),
        ),
    ]
