# Generated by Django 3.2.4 on 2026-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbase', '0034_auto_20260704_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='desc_optimized',
            field=models.BooleanField(default=None, null=True, verbose_name='描述已优化'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='title_optimized',
            field=models.BooleanField(default=None, null=True, verbose_name='标题已优化'),
        ),
    ]
